/*
 * PDCI: Institutional-Grade Data Center Supply Chain Intelligence
 *
 * Core logic and intellectual property by Wilton John Picou, III, Co-Founder of GloCon Solutions, LLLC.
 *
 * This software is for institutional use only. All rights reserved.
 */
import { Company, InvestmentTier, RiskLevel, Hotspot, GeopoliticalRiskLevel } from './types';

// This data is derived from the user-provided CSV and enriched with
// quantitative metrics as defined in the BI and Advanced Strategy documents.
export const companiesData: Company[] = [
  {
    Company: "TSMC",
    Ticker: "TSM",
    Exchange: "NYSE",
    Current_Price_USD: 195.92,
    Market_Cap_B: 1490,
    Shares_Outstanding_M: 25900,
    Float_Percent: 80,
    Category: "Semiconductors",
    Sub_Category: "Semiconductor Fabrication",
    Product_Component: "4nm-2nm AI Chip Manufacturing",
    Universal_Presence: "Yes - Manufactures 90%+ of all AI chips",
    Investment_Tier: InvestmentTier.MustBuy,
    Geographic_Presence: "Global: Taiwan (primary), Arizona (emerging)",
    Recent_Contracts_2024_2025: "NVIDIA Blackwell, AMD MI300, Apple, Broadcom - $33B Q3 2025 revenue",
    Growth_Driver: "Only advanced AI chip foundry",
    Risk_Level: RiskLevel.High,
    Competitive_Position: "Monopoly Position",
    Supply_Chain_Role: "Critical Bottleneck",
    Universal_Score: 100,
    Criticality: 10,
    Substitutability: "Impossible",
    YTD_Performance: 68.3,
    logoUrl: "https://logo.clearbit.com/tsmc.com",
    Country: "Taiwan",
    Substitutability_Score: 0,
    Supply_Chain_Depth_Score: 70,
    SCSI: 420,
    ESG_Score: 85,
    PE_Ratio: 34.2,
    Forward_PE: 25.1,
    Revenue_Growth_YoY: 16.5,
    Debt_to_Equity: 0.45,
    Graham_Score: 7,
    isBlueChip: true,
    Psych_Score: 92,
    Buy_Rank: 1,
    Probability_Of_Success: 95,
    Geopolitical_Risk: GeopoliticalRiskLevel.VeryHigh,
    Geopolitical_Risk_Score: 95,
    Geopolitical_Notes: "Primary operations and HQs in Taiwan face significant geopolitical tensions with China, posing a major supply chain risk."
  },
  {
    Company: "ASML Holding",
    Ticker: "ASML",
    Exchange: "NASDAQ",
    Current_Price_USD: 1025.78,
    Market_Cap_B: 408,
    Shares_Outstanding_M: 398,
    Float_Percent: 98,
    Category: "Semiconductors",
    Sub_Category: "Lithography Equipment",
    Product_Component: "EUV Lithography Machines",
    Universal_Presence: "Yes - Monopoly supplier to all advanced fabs",
    Investment_Tier: InvestmentTier.MustBuy,
    Geographic_Presence: "Global: Netherlands (HQ)",
    Recent_Contracts_2024_2025: "Exclusive supplier to TSMC, Intel, Samsung for advanced nodes",
    Growth_Driver: "Gate-All-Around (GAA) transition requires EUV",
    Risk_Level: RiskLevel.Moderate,
    Competitive_Position: "Monopoly",
    Supply_Chain_Role: "Critical Equipment Supplier",
    Universal_Score: 99,
    Criticality: 10,
    Substitutability: "Impossible",
    YTD_Performance: 38.8,
    logoUrl: "https://logo.clearbit.com/asml.com",
    Country: "Netherlands",
    Substitutability_Score: 0,
    Supply_Chain_Depth_Score: 70,
    SCSI: 450,
    ESG_Score: 89,
    PE_Ratio: 52.9,
    Forward_PE: 41.5,
    Revenue_Growth_YoY: -21.6,
    Debt_to_Equity: 0.28,
    Graham_Score: 8,
    isBlueChip: true,
    Psych_Score: 88,
    Buy_Rank: 3,
    Probability_Of_Success: 96,
    Geopolitical_Risk: GeopoliticalRiskLevel.High,
    Geopolitical_Risk_Score: 80,
    Geopolitical_Notes: "Subject to Western government (US, Netherlands) export controls to China, which impacts a major growth market."
  },
  {
    Company: "SK Hynix",
    Ticker: "000660.KS",
    Exchange: "Korea",
    Current_Price_USD: 148,
    Market_Cap_B: 102,
    Shares_Outstanding_M: 728,
    Float_Percent: 85,
    Category: "Semiconductors",
    Sub_Category: "HBM Memory",
    Product_Component: "HBM3E, HBM4 - 62% Market Share",
    Universal_Presence: "Yes - Integrated on every NVIDIA GPU",
    Investment_Tier: InvestmentTier.MustBuy,
    Geographic_Presence: "Global: Korea (primary), China",
    Recent_Contracts_2024_2025: "Sold out through 2026, NVIDIA exclusive supplier",
    Growth_Driver: "Controls AI memory bottleneck",
    Risk_Level: RiskLevel.Moderate,
    Competitive_Position: "Market Leader",
    Supply_Chain_Role: "Critical Bottleneck",
    Universal_Score: 98,
    Criticality: 10,
    Substitutability: "Impossible",
    YTD_Performance: 55.1,
    logoUrl: "https://logo.clearbit.com/skhynix.com",
    Country: "Korea",
    Substitutability_Score: 5,
    Supply_Chain_Depth_Score: 70,
    SCSI: 505,
    ESG_Score: 82,
    PE_Ratio: -20.5,
    Forward_PE: 8.5,
    Revenue_Growth_YoY: 144,
    Debt_to_Equity: 0.65,
    Graham_Score: 7,
    isBlueChip: false,
    Psych_Score: 95,
    Buy_Rank: 4,
    Probability_Of_Success: 93,
    Geopolitical_Risk: GeopoliticalRiskLevel.High,
    Geopolitical_Risk_Score: 75,
    Geopolitical_Notes: "Operations in South Korea face latent risk from North Korean instability. Also has manufacturing presence in China."
  },
  {
    Company: "Freeport-McMoRan",
    Ticker: "FCX",
    Exchange: "NYSE",
    Current_Price_USD: 43.82,
    Market_Cap_B: 62,
    Shares_Outstanding_M: 1420,
    Float_Percent: 99,
    Category: "Raw Materials",
    Sub_Category: "Copper Mining",
    Product_Component: "Copper Cathodes for All Wiring/PCBs",
    Universal_Presence: "Yes - 5-10 tons per MW capacity",
    Investment_Tier: InvestmentTier.MustBuy,
    Geographic_Presence: "Global: Americas, Indonesia",
    Recent_Contracts_2024_2025: "Copper shortage warning 6M tons by 2035",
    Growth_Driver: "Every cable, PCB, transformer uses copper",
    Risk_Level: RiskLevel.Moderate,
    Competitive_Position: "Major Producer",
    Supply_Chain_Role: "Raw Material Supplier",
    Universal_Score: 97,
    Criticality: 10,
    Substitutability: "Difficult",
    YTD_Performance: 28.2,
    logoUrl: "https://logo.clearbit.com/fcx.com",
    Country: "USA",
    Substitutability_Score: 30,
    Supply_Chain_Depth_Score: 100,
    SCSI: 380,
    ESG_Score: 65,
    PE_Ratio: 22.1,
    Forward_PE: 15.8,
    Revenue_Growth_YoY: 5.6,
    Debt_to_Equity: 0.4,
    Graham_Score: 7,
    isBlueChip: false,
    Psych_Score: 75,
    Buy_Rank: 6,
    Probability_Of_Success: 88,
    Geopolitical_Risk: GeopoliticalRiskLevel.High,
    Geopolitical_Risk_Score: 70,
    Geopolitical_Notes: "Significant mining operations in Indonesia (Grasberg mine) and Peru, regions with potential for political instability and resource nationalism."
  },
  {
    Company: "Nucor",
    Ticker: "NUE",
    Exchange: "NYSE",
    Current_Price_USD: 158.3,
    Market_Cap_B: 38,
    Shares_Outstanding_M: 240,
    Float_Percent: 99,
    Category: "Construction",
    Sub_Category: "Structural Steel",
    Product_Component: "EAF Steel for Racks, Frames, Trays",
    Universal_Presence: "Yes - Every rack, frame, structural element",
    Investment_Tier: InvestmentTier.MustBuy,
    Geographic_Presence: "North America: 300+ facilities",
    Recent_Contracts_2024_2025: "Multi-billion contracts for hyperscale AI DCs",
    Growth_Driver: "Largest NA steel producer",
    Risk_Level: RiskLevel.Conservative,
    Competitive_Position: "Market Leader",
    Supply_Chain_Role: "Structural Material",
    Universal_Score: 97,
    Criticality: 9,
    Substitutability: "Moderate",
    YTD_Performance: 22,
    logoUrl: "https://logo.clearbit.com/nucor.com",
    Country: "USA",
    Substitutability_Score: 60,
    Supply_Chain_Depth_Score: 100,
    SCSI: 120,
    ESG_Score: 81,
    PE_Ratio: 10.5,
    Forward_PE: 10,
    Revenue_Growth_YoY: -15,
    Debt_to_Equity: 0.35,
    Graham_Score: 9,
    isBlueChip: false,
    Psych_Score: 68,
    Buy_Rank: 7,
    Probability_Of_Success: 85,
    Geopolitical_Risk: GeopoliticalRiskLevel.Low,
    Geopolitical_Risk_Score: 10,
    Geopolitical_Notes: "Operations are almost entirely within North America, providing insulation from most global geopolitical conflicts."
  },
   {
    Company: "Southern Copper",
    Ticker: "SCCO",
    Exchange: "NYSE",
    Current_Price_USD: 93.05,
    Market_Cap_B: 71.9,
    Shares_Outstanding_M: 773,
    Float_Percent: 88,
    Category: "Raw Materials",
    Sub_Category: "Copper Mining",
    Product_Component: "Copper Wire Rod, Cathodes",
    Universal_Presence: "Yes - All power distribution uses copper",
    Investment_Tier: InvestmentTier.MustBuy,
    Geographic_Presence: "Americas: Peru, Mexico",
    Recent_Contracts_2024_2025: "Tia Maria $1.8B expansion starting 2027",
    Growth_Driver: "42% Americas market share",
    Risk_Level: RiskLevel.Moderate,
    Competitive_Position: "Regional Leader",
    Supply_Chain_Role: "Raw Material Supplier",
    Universal_Score: 96,
    Criticality: 10,
    Substitutability: "Difficult",
    YTD_Performance: 31,
    logoUrl: "https://logo.clearbit.com/southerncoppercorp.com",
    Country: "Mexico",
    Substitutability_Score: 30,
    Supply_Chain_Depth_Score: 100,
    SCSI: 370,
    ESG_Score: 68,
    PE_Ratio: 30.2,
    Forward_PE: 24,
    Revenue_Growth_YoY: 8.1,
    Debt_to_Equity: 0.5,
    Graham_Score: 6,
    isBlueChip: false,
    Psych_Score: 72,
    Buy_Rank: 8,
    Probability_Of_Success: 87,
    Geopolitical_Risk: GeopoliticalRiskLevel.Medium,
    Geopolitical_Risk_Score: 60,
    Geopolitical_Notes: "Primary mines in Peru and Mexico, countries that have experienced periods of political and social unrest affecting mining operations."
  },
  {
    Company: "MP Materials",
    Ticker: "MP",
    Exchange: "NYSE",
    Current_Price_USD: 28.35,
    Market_Cap_B: 12.36,
    Shares_Outstanding_M: 436,
    Float_Percent: 82,
    Category: "Raw Materials",
    Sub_Category: "Rare Earth Elements",
    Product_Component: "NdPr for Magnets in HDDs, Fans, Motors",
    Universal_Presence: "Yes - Every HDD, fan, motor has rare earth magnets",
    Investment_Tier: InvestmentTier.MustBuy,
    Geographic_Presence: "North America: California only US source",
    Recent_Contracts_2024_2025: "DoD multi-billion 10X Facility, Apple $500M investment",
    Growth_Driver: "Only US rare earth producer",
    Risk_Level: RiskLevel.High,
    Competitive_Position: "US Monopoly",
    Supply_Chain_Role: "Strategic Material",
    Universal_Score: 95,
    Criticality: 9,
    Substitutability: "Impossible",
    YTD_Performance: -10,
    logoUrl: "https://logo.clearbit.com/mpmaterials.com",
    Country: "USA",
    Substitutability_Score: 0,
    Supply_Chain_Depth_Score: 100,
    SCSI: 340,
    ESG_Score: 50,
    PE_Ratio: 55,
    Forward_PE: 30,
    Revenue_Growth_YoY: -35,
    Debt_to_Equity: 1.2,
    Graham_Score: 4,
    isBlueChip: false,
    Psych_Score: 85,
    Buy_Rank: 9,
    Probability_Of_Success: 78,
    Geopolitical_Risk: GeopoliticalRiskLevel.Medium,
    Geopolitical_Risk_Score: 50,
    Geopolitical_Notes: "Operates in a sector dominated by China. While a US asset, its pricing and market are heavily influenced by Chinese policy."
  },
  {
    Company: "Broadcom",
    Ticker: "AVGO",
    Exchange: "NASDAQ",
    Current_Price_USD: 167.5,
    Market_Cap_B: 1010,
    Shares_Outstanding_M: 6030,
    Float_Percent: 85,
    Category: "Networking",
    Sub_Category: "Switching Silicon",
    Product_Component: "Tomahawk 5/4 ASICs for Switches",
    Universal_Presence: "Yes - Powers Arista, Cisco, most DC switches",
    Investment_Tier: InvestmentTier.HighConviction,
    Geographic_Presence: "Global: Fabless design",
    Recent_Contracts_2024_2025: "51.2T switch capacity ASICs, custom AI accelerators",
    Growth_Driver: "Silicon behind most networking gear",
    Risk_Level: RiskLevel.Moderate,
    Competitive_Position: "Oligopoly",
    Supply_Chain_Role: "Component Supplier",
    Universal_Score: 94,
    Criticality: 10,
    Substitutability: "Difficult",
    YTD_Performance: 49.3,
    logoUrl: "https://logo.clearbit.com/broadcom.com",
    Country: "USA",
    Substitutability_Score: 25,
    Supply_Chain_Depth_Score: 70,
    SCSI: 320,
    ESG_Score: 68,
    PE_Ratio: 58.1,
    Forward_PE: 33.7,
    Revenue_Growth_YoY: 43,
    Debt_to_Equity: 1.05,
    Graham_Score: 6,
    isBlueChip: true,
    Psych_Score: 82,
    Buy_Rank: 10,
    Probability_Of_Success: 91,
    Geopolitical_Risk: GeopoliticalRiskLevel.Medium,
    Geopolitical_Risk_Score: 40,
    Geopolitical_Notes: "As a fabless company, it relies on foundries like TSMC in Taiwan, inheriting some of their geopolitical risk."
  },
  {
    Company: "Amphenol",
    Ticker: "APH",
    Exchange: "NYSE",
    Current_Price_USD: 138.11,
    Market_Cap_B: 163.35,
    Shares_Outstanding_M: 1180,
    Float_Percent: 99,
    Category: "Interconnects",
    Sub_Category: "Connectors, Cables",
    Product_Component: "High-Frequency Interconnects, 400G/800G",
    Universal_Presence: "Yes - Every device uses Amphenol connectors",
    Investment_Tier: InvestmentTier.HighConviction,
    Geographic_Presence: "Global: 100+ countries",
    Recent_Contracts_2024_2025: "400G/800G adoption, +54% spike 2024",
    Growth_Driver: "Universal connector presence",
    Risk_Level: RiskLevel.Conservative,
    Competitive_Position: "Market Leader",
    Supply_Chain_Role: "Universal Component",
    Universal_Score: 94,
    Criticality: 10,
    Substitutability: "Difficult",
    YTD_Performance: 54,
    logoUrl: "https://logo.clearbit.com/amphenol.com",
    Country: "USA",
    Substitutability_Score: 30,
    Supply_Chain_Depth_Score: 70,
    SCSI: 260,
    ESG_Score: 74,
    PE_Ratio: 30.5,
    Forward_PE: 26.8,
    Revenue_Growth_YoY: 2.5,
    Debt_to_Equity: 0.5,
    Graham_Score: 6,
    isBlueChip: false,
    Psych_Score: 78,
    Buy_Rank: 11,
    Probability_Of_Success: 90,
    Geopolitical_Risk: GeopoliticalRiskLevel.Low,
    Geopolitical_Risk_Score: 20,
    Geopolitical_Notes: "Highly diversified global manufacturing footprint mitigates single-region geopolitical risks."
  },
  {
    Company: "Vertiv",
    Ticker: "VRT",
    Exchange: "NYSE",
    Current_Price_USD: 118.5,
    Market_Cap_B: 45,
    Shares_Outstanding_M: 380,
    Float_Percent: 98,
    Category: "Power & Cooling",
    Sub_Category: "UPS, PDUs, Cooling",
    Product_Component: "Liebert UPS, Direct-to-Chip Liquid Cooling",
    Universal_Presence: "Yes - #1 ABI ranking, all DCs need UPS/cooling",
    Investment_Tier: InvestmentTier.HighConviction,
    Geographic_Presence: "Global: Americas, EMEA, Asia",
    Recent_Contracts_2024_2025: "Liquid cooling portfolio for 120kW AI racks",
    Growth_Driver: "Integrated power/thermal management",
    Risk_Level: RiskLevel.Moderate,
    Competitive_Position: "Market Leader",
    Supply_Chain_Role: "Critical Infrastructure",
    Universal_Score: 93,
    Criticality: 10,
    Substitutability: "Moderate",
    YTD_Performance: 89.5,
    logoUrl: "https://logo.clearbit.com/vertiv.com",
    Country: "USA",
    Substitutability_Score: 40,
    Supply_Chain_Depth_Score: 40,
    SCSI: 280,
    ESG_Score: 60,
    PE_Ratio: 52.7,
    Forward_PE: 30.1,
    Revenue_Growth_YoY: 15.2,
    Debt_to_Equity: 2.5,
    Graham_Score: 3,
    isBlueChip: false,
    Psych_Score: 90,
    Buy_Rank: 12,
    Probability_Of_Success: 89,
    Geopolitical_Risk: GeopoliticalRiskLevel.Low,
    Geopolitical_Risk_Score: 25,
    Geopolitical_Notes: "Global manufacturing presence provides resilience. Moderate risk from general supply chain disruptions."
  },
    {
    Company: "Prysmian",
    Ticker: "PRY.MI",
    Exchange: "Milan",
    Current_Price_USD: 95,
    Market_Cap_B: 27.5,
    Shares_Outstanding_M: 287,
    Float_Percent: 100,
    Category: "Interconnects",
    Sub_Category: "Power Cables",
    Product_Component: "HV/MV Power Distribution Cables",
    Universal_Presence: "Yes - World's largest cable mfg, all DC power",
    Investment_Tier: InvestmentTier.HighConviction,
    Geographic_Presence: "Global: Largest cable company",
    Recent_Contracts_2024_2025: "€382.5M contracts 2025, expansion globally",
    Growth_Driver: "Main power feeds, backbone infrastructure",
    Risk_Level: RiskLevel.Moderate,
    Competitive_Position: "Global Leader",
    Supply_Chain_Role: "Power Distribution",
    Universal_Score: 93,
    Criticality: 9,
    Substitutability: "Moderate",
    YTD_Performance: 35,
    logoUrl: "https://logo.clearbit.com/prysmiangroup.com",
    Country: "Italy",
    Substitutability_Score: 45,
    Supply_Chain_Depth_Score: 70,
    SCSI: 240,
    ESG_Score: 84,
    PE_Ratio: 18,
    Forward_PE: 15,
    Revenue_Growth_YoY: 6,
    Debt_to_Equity: 0.6,
    Graham_Score: 7,
    isBlueChip: false,
    Psych_Score: 70,
    Buy_Rank: 13,
    Probability_Of_Success: 86,
    Geopolitical_Risk: GeopoliticalRiskLevel.Medium,
    Geopolitical_Risk_Score: 35,
    Geopolitical_Notes: "European base provides stability, but global operations are exposed to various regional risks and tariffs."
  },
  {
    Company: "Arista Networks",
    Ticker: "ANET",
    Exchange: "NYSE",
    Current_Price_USD: 398.6,
    Market_Cap_B: 125,
    Shares_Outstanding_M: 314,
    Float_Percent: 95,
    Category: "Networking",
    Sub_Category: "Ethernet Switches",
    Product_Component: "400G/800G Switches for AI Spine",
    Universal_Presence: "Yes - Every AI cluster uses high-speed Ethernet",
    Investment_Tier: InvestmentTier.HighConviction,
    Geographic_Presence: "Global: Cloud-native deployments",
    Recent_Contracts_2024_2025: "5 major AI trials, 70% cloud DC switching share",
    Growth_Driver: "Ethernet beating InfiniBand for AI",
    Risk_Level: RiskLevel.Moderate,
    Competitive_Position: "Market Leader",
    Supply_Chain_Role: "Critical Infrastructure",
    Universal_Score: 92,
    Criticality: 9,
    Substitutability: "Difficult",
    YTD_Performance: 34.2,
    logoUrl: "https://logo.clearbit.com/arista.com",
    Country: "USA",
    Substitutability_Score: 30,
    Supply_Chain_Depth_Score: 40,
    SCSI: 200,
    ESG_Score: 71,
    PE_Ratio: 45.1,
    Forward_PE: 35.8,
    Revenue_Growth_YoY: 16.3,
    Debt_to_Equity: 0,
    Graham_Score: 6,
    isBlueChip: false,
    Psych_Score: 84,
    Buy_Rank: 14,
    Probability_Of_Success: 89,
    Geopolitical_Risk: GeopoliticalRiskLevel.Medium,
    Geopolitical_Risk_Score: 45,
    Geopolitical_Notes: "Relies on overseas manufacturing and components from Asia, exposing it to supply chain and tariff risks."
  },
  {
    Company: "Super Micro",
    Ticker: "SMCI",
    Exchange: "NASDAQ",
    Current_Price_USD: 850.5,
    Market_Cap_B: 50.1,
    Shares_Outstanding_M: 58.9,
    Float_Percent: 65,
    Category: "Hardware",
    Sub_Category: "AI Servers",
    Product_Component: "GPU Servers, Rack-Scale Systems",
    Universal_Presence: "Yes - #1 ABI agility, fastest new GPU adoption",
    Investment_Tier: InvestmentTier.OnRadar,
    Geographic_Presence: "Global: Design US, Asia manufacturing",
    Recent_Contracts_2024_2025: "Blackwell Ultra volume production Sept 2025",
    Growth_Driver: "First to market with new platforms",
    Risk_Level: RiskLevel.Aggressive,
    Competitive_Position: "Agile Leader",
    Supply_Chain_Role: "System Integrator",
    Universal_Score: 92,
    Criticality: 8,
    Substitutability: "Moderate",
    YTD_Performance: 190.2,
    logoUrl: "https://logo.clearbit.com/smci.com",
    Country: "USA",
    Substitutability_Score: 50,
    Supply_Chain_Depth_Score: 40,
    SCSI: 70,
    ESG_Score: 55,
    PE_Ratio: 45.8,
    Forward_PE: 22.3,
    Revenue_Growth_YoY: 200,
    Debt_to_Equity: 0.1,
    Graham_Score: 4,
    isBlueChip: false,
    Psych_Score: 96,
    Buy_Rank: 15,
    Probability_Of_Success: 75,
    Geopolitical_Risk: GeopoliticalRiskLevel.Medium,
    Geopolitical_Risk_Score: 55,
    Geopolitical_Notes: "Heavy reliance on manufacturing in Taiwan and components from the APAC region creates significant geopolitical risk exposure."
  },
  {
    Company: "GlobalWafers",
    Ticker: "6488.TWO",
    Exchange: "Taiwan",
    Current_Price_USD: 18,
    Market_Cap_B: 16,
    Shares_Outstanding_M: 887,
    Float_Percent: 70,
    Category: "Semiconductors",
    Sub_Category: "Silicon Wafers",
    Product_Component: "300mm Silicon Wafer Substrates",
    Universal_Presence: "Yes - Every chip starts as a wafer",
    Investment_Tier: InvestmentTier.MustBuy,
    Geographic_Presence: "Global: Taiwan, Texas (new)",
    Recent_Contracts_2024_2025: "$3B+ expansion, Texas fab opened May 2025",
    Growth_Driver: "Only 3 global suppliers for advanced wafers",
    Risk_Level: RiskLevel.High,
    Competitive_Position: "Oligopoly (Top 3)",
    Supply_Chain_Role: "Raw Material Supplier",
    Universal_Score: 92,
    Criticality: 9,
    Substitutability: "Difficult",
    YTD_Performance: -5.2,
    logoUrl: "https://logo.clearbit.com/sas-globalwafers.com",
    Country: "Taiwan",
    Substitutability_Score: 30,
    Supply_Chain_Depth_Score: 100,
    SCSI: 300,
    ESG_Score: 72,
    PE_Ratio: 12.1,
    Forward_PE: 10.5,
    Revenue_Growth_YoY: -18.7,
    Debt_to_Equity: 0.75,
    Graham_Score: 9,
    isBlueChip: false,
    Psych_Score: 65,
    Buy_Rank: 16,
    Probability_Of_Success: 84,
    Geopolitical_Risk: GeopoliticalRiskLevel.VeryHigh,
    Geopolitical_Risk_Score: 90,
    Geopolitical_Notes: "Taiwanese headquarters and significant operations create the same high level of geopolitical risk as TSMC."
  },
  {
    Company: "SUMCO",
    Ticker: "3436.T",
    Exchange: "Tokyo",
    Current_Price_USD: 12.4,
    Market_Cap_B: 5,
    Shares_Outstanding_M: 405,
    Float_Percent: 85,
    Category: "Semiconductors",
    Sub_Category: "Silicon Wafers",
    Product_Component: "300mm Epitaxial Wafers",
    Universal_Presence: "Yes - Premium wafer supplier",
    Investment_Tier: InvestmentTier.MustBuy,
    Geographic_Presence: "Global: Japan, US (Oregon)",
    Recent_Contracts_2024_2025: "Advanced 300mm capacity expansion 2024-2025",
    Growth_Driver: "Elite wafer quality for AI/HPC",
    Risk_Level: RiskLevel.Moderate,
    Competitive_Position: "Oligopoly (Top 3)",
    Supply_Chain_Role: "Raw Material Supplier",
    Universal_Score: 91,
    Criticality: 9,
    Substitutability: "Difficult",
    YTD_Performance: 15.1,
    logoUrl: "https://logo.clearbit.com/sumcosi.com",
    Country: "Japan",
    Substitutability_Score: 30,
    Supply_Chain_Depth_Score: 100,
    SCSI: 290,
    ESG_Score: 78,
    PE_Ratio: 14.5,
    Forward_PE: 12,
    Revenue_Growth_YoY: -15,
    Debt_to_Equity: 0.3,
    Graham_Score: 8,
    isBlueChip: false,
    Psych_Score: 67,
    Buy_Rank: 17,
    Probability_Of_Success: 85,
    Geopolitical_Risk: GeopoliticalRiskLevel.Medium,
    Geopolitical_Risk_Score: 30,
    Geopolitical_Notes: "Japanese base offers stability, but proximity to regional tensions in Asia poses a moderate risk."
  },
  {
    Company: "Eaton",
    Ticker: "ETN",
    Exchange: "NYSE",
    Current_Price_USD: 344.8,
    Market_Cap_B: 136,
    Shares_Outstanding_M: 395,
    Float_Percent: 99,
    Category: "Power & Cooling",
    Sub_Category: "UPS, Switchgear",
    Product_Component: "UPS Systems, Power Distribution",
    Universal_Presence: "Yes - Universal power management",
    Investment_Tier: InvestmentTier.HighConviction,
    Geographic_Presence: "Global: Industrial conglomerate",
    Recent_Contracts_2024_2025: "41-43% market share with Schneider, Vertiv",
    Growth_Driver: "Makes own circuit breakers (supply chain)",
    Risk_Level: RiskLevel.Conservative,
    Competitive_Position: "Market Leader",
    Supply_Chain_Role: "Critical Infrastructure",
    Universal_Score: 90,
    Criticality: 9,
    Substitutability: "Moderate",
    YTD_Performance: 39.1,
    logoUrl: "https://logo.clearbit.com/eaton.com",
    Country: "Ireland",
    Substitutability_Score: 60,
    Supply_Chain_Depth_Score: 40,
    SCSI: 220,
    ESG_Score: 80,
    PE_Ratio: 36.8,
    Forward_PE: 28.9,
    Revenue_Growth_YoY: 8,
    Debt_to_Equity: 0.6,
    Graham_Score: 8,
    isBlueChip: false,
    Psych_Score: 74,
    Buy_Rank: 18,
    Probability_Of_Success: 88,
    Geopolitical_Risk: GeopoliticalRiskLevel.Low,
    Geopolitical_Risk_Score: 15,
    Geopolitical_Notes: "Irish domicile and diversified global footprint provide significant resilience against single-point geopolitical failures."
  },
  {
    Company: "Murata",
    Ticker: "6981.T",
    Exchange: "Tokyo",
    Current_Price_USD: 19,
    Market_Cap_B: 34,
    Shares_Outstanding_M: 1790,
    Float_Percent: 80,
    Category: "Components",
    Sub_Category: "Passive Electronics",
    Product_Component: "MLCC Capacitors, Resistors",
    Universal_Presence: "Yes - Billions on every motherboard/PSU/board",
    Investment_Tier: InvestmentTier.OnRadar,
    Geographic_Presence: "Global: Japan base, worldwide",
    Recent_Contracts_2024_2025: "Supply chain localization, sustainability push",
    Growth_Driver: "Every PCB has Murata components",
    Risk_Level: RiskLevel.Aggressive,
    Competitive_Position: "Component Leader",
    Supply_Chain_Role: "Universal Component",
    Universal_Score: 90,
    Criticality: 9,
    Substitutability: "Moderate",
    YTD_Performance: 28,
    logoUrl: "https://logo.clearbit.com/murata.com",
    Country: "Japan",
    Substitutability_Score: 40,
    Supply_Chain_Depth_Score: 70,
    SCSI: 190,
    ESG_Score: 86,
    PE_Ratio: 18,
    Forward_PE: 16,
    Revenue_Growth_YoY: -5,
    Debt_to_Equity: 0.05,
    Graham_Score: 7,
    isBlueChip: false,
    Psych_Score: 71,
    Buy_Rank: 19,
    Probability_Of_Success: 82,
    Geopolitical_Risk: GeopoliticalRiskLevel.Medium,
    Geopolitical_Risk_Score: 30,
    Geopolitical_Notes: "Stable Japanese base, but high concentration of manufacturing in Asia exposes it to regional supply chain risks."
  },
    {
    Company: "TE Connectivity",
    Ticker: "TEL",
    Exchange: "NYSE",
    Current_Price_USD: 145.6,
    Market_Cap_B: 45,
    Shares_Outstanding_M: 309,
    Float_Percent: 99.5,
    Category: "Interconnects",
    Sub_Category: "Connectors, Sensors",
    Product_Component: "High-speed I/O connectors, Fiber Optics",
    Universal_Presence: "Ubiquitous",
    Investment_Tier: InvestmentTier.HighConviction,
    Geographic_Presence: "Global",
    Recent_Contracts_2024_2025: "High-speed I/O connectors for next-gen servers",
    Growth_Driver: "Higher data rates (800G/1.6T) driving connector demand",
    Risk_Level: RiskLevel.Conservative,
    Competitive_Position: "Established Leader",
    Supply_Chain_Role: "Core Component Supplier",
    Universal_Score: 90,
    Criticality: 8,
    Substitutability: "Difficult",
    YTD_Performance: 10.1,
    logoUrl: "https://logo.clearbit.com/te.com",
    Country: "Switzerland",
    Substitutability_Score: 30,
    Supply_Chain_Depth_Score: 70,
    SCSI: 210,
    ESG_Score: 84,
    PE_Ratio: 22,
    Forward_PE: 19.5,
    Revenue_Growth_YoY: -6.5,
    Debt_to_Equity: 0.35,
    Graham_Score: 7,
    isBlueChip: false,
    Psych_Score: 73,
    Buy_Rank: 20,
    Probability_Of_Success: 87,
    Geopolitical_Risk: GeopoliticalRiskLevel.Low,
    Geopolitical_Risk_Score: 15,
    Geopolitical_Notes: "Swiss domicile and broad global manufacturing base reduce exposure to any single point of geopolitical failure."
  },
    {
    Company: "NVIDIA",
    Ticker: "NVDA",
    Exchange: "NASDAQ",
    Current_Price_USD: 120.89,
    Market_Cap_B: 2975,
    Shares_Outstanding_M: 24600,
    Float_Percent: 75.8,
    Category: "Semiconductors",
    Sub_Category: "GPUs",
    Product_Component: "H100/B200 Tensor Core GPUs",
    Universal_Presence: "Ubiquitous",
    Investment_Tier: InvestmentTier.MustBuy,
    Geographic_Presence: "Global",
    Recent_Contracts_2024_2025: "Major cloud providers (AWS, MSFT, GOOGL)",
    Growth_Driver: "Generative AI demand",
    Risk_Level: RiskLevel.Moderate,
    Competitive_Position: "Dominant Market Leader",
    Supply_Chain_Role: "Core Component Supplier",
    Universal_Score: 99,
    Criticality: 10,
    Substitutability: "Impossible",
    YTD_Performance: 144.5,
    logoUrl: "https://logo.clearbit.com/nvidia.com",
    Country: "USA",
    Substitutability_Score: 5,
    Supply_Chain_Depth_Score: 70,
    SCSI: 390,
    ESG_Score: 78,
    PE_Ratio: 70.5,
    Forward_PE: 45.2,
    Revenue_Growth_YoY: 262.1,
    Debt_to_Equity: 0.38,
    Graham_Score: 5,
    isBlueChip: true,
    Psych_Score: 98,
    Buy_Rank: 2,
    Probability_Of_Success: 94,
    Geopolitical_Risk: GeopoliticalRiskLevel.VeryHigh,
    Geopolitical_Risk_Score: 90,
    Geopolitical_Notes: "Complete dependency on TSMC for manufacturing its advanced GPUs creates a severe single-point-of-failure risk tied to Taiwan."
  },
  {
    Company: "Parker-Hannifin",
    Ticker: "PH",
    Exchange: "NYSE",
    Current_Price_USD: 520.15,
    Market_Cap_B: 65,
    Shares_Outstanding_M: 125,
    Float_Percent: 99,
    Category: "Power & Cooling",
    Sub_Category: "Fluid & Gas Handling",
    Product_Component: "Valves, Hoses, Fittings for Liquid Cooling",
    Universal_Presence: "Yes - Essential for all liquid cooling systems",
    Investment_Tier: InvestmentTier.OnRadar,
    Geographic_Presence: "Global",
    Recent_Contracts_2024_2025: "Increased demand from liquid cooling OEMs like Vertiv",
    Growth_Driver: "Shift to direct-to-chip and immersion cooling",
    Risk_Level: RiskLevel.Conservative,
    Competitive_Position: "Market Leader",
    Supply_Chain_Role: "Component Supplier",
    Universal_Score: 89,
    Criticality: 8,
    Substitutability: "Difficult",
    YTD_Performance: 18.5,
    logoUrl: "https://logo.clearbit.com/parker.com",
    Country: "USA",
    Substitutability_Score: 35,
    Supply_Chain_Depth_Score: 70,
    SCSI: 180,
    ESG_Score: 78,
    PE_Ratio: 24.1,
    Forward_PE: 19.8,
    Revenue_Growth_YoY: 3.2,
    Debt_to_Equity: 0.8,
    Graham_Score: 7,
    isBlueChip: false,
    Psych_Score: 69,
    Buy_Rank: 21,
    Probability_Of_Success: 83,
    Geopolitical_Risk: GeopoliticalRiskLevel.Low,
    Geopolitical_Risk_Score: 20,
    Geopolitical_Notes: "Diversified industrial with a strong US base and global footprint, making it resilient to specific regional issues."
  },
  {
    Company: "Kingspan Group",
    Ticker: "KGP.L",
    Exchange: "LSE",
    Current_Price_USD: 95.50, // Converted from EUR
    Market_Cap_B: 17.5,
    Shares_Outstanding_M: 183,
    Float_Percent: 70,
    Category: "Construction",
    Sub_Category: "Physical Infrastructure",
    Product_Component: "Raised Access Flooring & Insulated Panels",
    Universal_Presence: "Yes - Standard in all modern data centers",
    Investment_Tier: InvestmentTier.OnRadar,
    Geographic_Presence: "Global",
    Recent_Contracts_2024_2025: "Major supplier for new hyperscale builds in Europe and US",
    Growth_Driver: "Data center construction boom requires specialized flooring",
    Risk_Level: RiskLevel.Moderate,
    Competitive_Position: "Market Leader",
    Supply_Chain_Role: "Structural Material",
    Universal_Score: 86,
    Criticality: 7,
    Substitutability: "Moderate",
    YTD_Performance: 22.1,
    logoUrl: "https://logo.clearbit.com/kingspan.com",
    Country: "Ireland",
    Substitutability_Score: 50,
    Supply_Chain_Depth_Score: 70,
    SCSI: 130,
    ESG_Score: 85,
    PE_Ratio: 25.0,
    Forward_PE: 20.5,
    Revenue_Growth_YoY: -5.0,
    Debt_to_Equity: 0.4,
    Graham_Score: 6,
    isBlueChip: false,
    Psych_Score: 64,
    Buy_Rank: 22,
    Probability_Of_Success: 80,
    Geopolitical_Risk: GeopoliticalRiskLevel.Low,
    Geopolitical_Risk_Score: 15,
    Geopolitical_Notes: "Irish base and focus on EU/US markets provide a stable operating environment."
  },
  {
    Company: "Nextracker",
    Ticker: "NXT",
    Exchange: "NASDAQ",
    Current_Price_USD: 55.40,
    Market_Cap_B: 8.1,
    Shares_Outstanding_M: 146,
    Float_Percent: 85,
    Category: "Power & Cooling",
    Sub_Category: "Renewable Energy",
    Product_Component: "Solar Tracking Systems for Power Generation",
    Universal_Presence: "Growing - Key for DC renewable PPAs",
    Investment_Tier: InvestmentTier.OnRadar,
    Geographic_Presence: "Global",
    Recent_Contracts_2024_2025: "Contracts for large solar farms powering new data centers",
    Growth_Driver: "Push for 24/7 carbon-free energy for data centers",
    Risk_Level: RiskLevel.Aggressive,
    Competitive_Position: "Market Leader",
    Supply_Chain_Role: "Critical Infrastructure",
    Universal_Score: 82,
    Criticality: 6,
    Substitutability: "Difficult",
    YTD_Performance: 35.7,
    logoUrl: "https://logo.clearbit.com/nextracker.com",
    Country: "USA",
    Substitutability_Score: 40,
    Supply_Chain_Depth_Score: 40,
    SCSI: 150,
    ESG_Score: 70,
    PE_Ratio: 28.3,
    Forward_PE: 22.0,
    Revenue_Growth_YoY: 30.1,
    Debt_to_Equity: 0.1,
    Graham_Score: 5,
    isBlueChip: false,
    Psych_Score: 77,
    Buy_Rank: 23,
    Probability_Of_Success: 79,
    Geopolitical_Risk: GeopoliticalRiskLevel.Low,
    Geopolitical_Risk_Score: 25,
    Geopolitical_Notes: "US-based, but relies on global supply chains for components, which can be affected by tariffs and trade disputes."
  },
  { Company: "Siemens", Ticker: "SIEGY", Exchange: "OTC", Current_Price_USD: 180.1, Market_Cap_B: 145, YTD_Performance: 12.5, logoUrl: "https://logo.clearbit.com/siemens.com", Country: "Germany", isBlueChip: false, Shares_Outstanding_M: 805, Float_Percent: 99, Category: "Power & Cooling", Sub_Category: "UPS, Switchgear", Product_Component: "Industrial Automation, Switchgear", Universal_Presence: "Yes", Investment_Tier: InvestmentTier.OnRadar, Geographic_Presence: "Global", Recent_Contracts_2024_2025: "N/A", Growth_Driver: "Industrial Conglomerate", Risk_Level: RiskLevel.Conservative, Competitive_Position: "Market Leader", Supply_Chain_Role: "Critical Infrastructure", Universal_Score: 88, Criticality: 8, Substitutability: "Moderate", Substitutability_Score: 50, Supply_Chain_Depth_Score: 40, SCSI: 150, PE_Ratio: 15.6, Forward_PE: 14.1, Revenue_Growth_YoY: 5.2, Debt_to_Equity: 0.55, Graham_Score: 7, ESG_Score: 83, Psych_Score: 68, Buy_Rank: 24, Probability_Of_Success: 85, Geopolitical_Risk: GeopoliticalRiskLevel.Medium, Geopolitical_Risk_Score: 35, Geopolitical_Notes: "Exposed to European energy policy and economic conditions. Global operations can be affected by trade disputes." },
  { Company: "Atkore", Ticker: "ATKR", Exchange: "NYSE", Current_Price_USD: 140.5, Market_Cap_B: 4.8, YTD_Performance: -8.2, logoUrl: "https://logo.clearbit.com/atkore.com", Country: "USA", isBlueChip: false, Shares_Outstanding_M: 34, Float_Percent: 98, Category: "Construction", Sub_Category: "Physical Infrastructure", Product_Component: "Cable Trays, Conduits", Universal_Presence: "Yes", Investment_Tier: InvestmentTier.OnRadar, Geographic_Presence: "North America", Recent_Contracts_2024_2025: "N/A", Growth_Driver: "Data Center Construction", Risk_Level: RiskLevel.Moderate, Competitive_Position: "Market Leader", Supply_Chain_Role: "Structural Material", Universal_Score: 84, Criticality: 7, Substitutability: "Moderate", Substitutability_Score: 60, Supply_Chain_Depth_Score: 70, SCSI: 110, PE_Ratio: 8.5, Forward_PE: 8, Revenue_Growth_YoY: -10.1, Debt_to_Equity: 0.9, Graham_Score: 8, ESG_Score: 60, Psych_Score: 62, Buy_Rank: 25, Probability_Of_Success: 77, Geopolitical_Risk: GeopoliticalRiskLevel.Low, Geopolitical_Risk_Score: 10, Geopolitical_Notes: "Primarily North American focus insulates it from direct international geopolitical events." },
  { Company: "nVent Electric", Ticker: "NVT", Exchange: "NYSE", Current_Price_USD: 78.9, Market_Cap_B: 13, YTD_Performance: 25.1, logoUrl: "https://logo.clearbit.com/nvent.com", Country: "UK", isBlueChip: false, Shares_Outstanding_M: 165, Float_Percent: 99, Category: "Power & Cooling", Sub_Category: "Enclosures & Racks", Product_Component: "Enclosures, Racks, Cooling", Universal_Presence: "Yes", Investment_Tier: InvestmentTier.OnRadar, Geographic_Presence: "Global", Recent_Contracts_2024_2025: "N/A", Growth_Driver: "Liquid Cooling Adoption", Risk_Level: RiskLevel.Moderate, Competitive_Position: "Established Player", Supply_Chain_Role: "Critical Infrastructure", Universal_Score: 87, Criticality: 8, Substitutability: "Moderate", Substitutability_Score: 55, Supply_Chain_Depth_Score: 40, SCSI: 140, PE_Ratio: 23.5, Forward_PE: 20.1, Revenue_Growth_YoY: 10.3, Debt_to_Equity: 0.4, Graham_Score: 6, ESG_Score: 75, Psych_Score: 70, Buy_Rank: 26, Probability_Of_Success: 81, Geopolitical_Risk: GeopoliticalRiskLevel.Low, Geopolitical_Risk_Score: 20, Geopolitical_Notes: "UK-domiciled but operates globally, providing a diversified manufacturing and sales base." },
  { Company: "Credo Technology", Ticker: "CRDO", Exchange: "NASDAQ", Current_Price_USD: 28.61, Market_Cap_B: 4.8, YTD_Performance: 110.4, logoUrl: "https://logo.clearbit.com/credosemi.com", Country: "USA", isBlueChip: false, Shares_Outstanding_M: 168, Float_Percent: 75, Category: "Interconnects", Sub_Category: "Active Electrical Cables", Product_Component: "AECs, SerDes Chiplets", Universal_Presence: "Yes", Investment_Tier: InvestmentTier.OnRadar, Geographic_Presence: "Global", Recent_Contracts_2024_2025: "xAI Memphis contract", Growth_Driver: "AI Cluster Interconnects", Risk_Level: RiskLevel.Aggressive, Competitive_Position: "Niche Leader", Supply_Chain_Role: "Component Supplier", Universal_Score: 92, Criticality: 8, Substitutability: "Difficult", Substitutability_Score: 35, Supply_Chain_Depth_Score: 70, SCSI: 180, PE_Ratio: 120.5, Forward_PE: 55.2, Revenue_Growth_YoY: 85.6, Debt_to_Equity: 0.05, Graham_Score: 2, ESG_Score: 58, Psych_Score: 93, Buy_Rank: 5, Probability_Of_Success: 76, Geopolitical_Risk: GeopoliticalRiskLevel.Medium, Geopolitical_Risk_Score: 45, Geopolitical_Notes: "Fabless model means dependence on Asian foundries, creating supply chain risk related to geopolitical events." },
  { Company: "Seagate", Ticker: "STX", Exchange: "NASDAQ", Current_Price_USD: 105.2, Market_Cap_B: 21, YTD_Performance: 21.5, logoUrl: "https://logo.clearbit.com/seagate.com", Country: "Ireland", isBlueChip: false, Shares_Outstanding_M: 200, Float_Percent: 99, Category: "Hardware", Sub_Category: "Storage", Product_Component: "HDDs, SSDs", Universal_Presence: "Yes", Investment_Tier: InvestmentTier.OnRadar, Geographic_Presence: "Global", Recent_Contracts_2024_2025: "N/A", Growth_Driver: "Cold Storage for AI Data", Risk_Level: RiskLevel.Moderate, Competitive_Position: "Oligopoly", Supply_Chain_Role: "System Integrator", Universal_Score: 80, Criticality: 7, Substitutability: "Moderate", Substitutability_Score: 60, Supply_Chain_Depth_Score: 40, SCSI: 90, PE_Ratio: -50.1, Forward_PE: 15.3, Revenue_Growth_YoY: -11.4, Debt_to_Equity: 5.5, Graham_Score: 3, ESG_Score: 79, Psych_Score: 60, Buy_Rank: 27, Probability_Of_Success: 70, Geopolitical_Risk: GeopoliticalRiskLevel.Medium, Geopolitical_Risk_Score: 40, Geopolitical_Notes: "Manufacturing facilities in Asia (e.g., Thailand) are subject to regional stability and supply chain disruptions." },
  { Company: "Western Digital", Ticker: "WDC", Exchange: "NASDAQ", Current_Price_USD: 82.4, Market_Cap_B: 25, YTD_Performance: 68.9, logoUrl: "https://logo.clearbit.com/westerndigital.com", Country: "USA", isBlueChip: false, Shares_Outstanding_M: 303, Float_Percent: 98, Category: "Hardware", Sub_Category: "Storage", Product_Component: "HDDs, SSDs, NAND Flash", Universal_Presence: "Yes", Investment_Tier: InvestmentTier.OnRadar, Geographic_Presence: "Global", Recent_Contracts_2024_2025: "N/A", Growth_Driver: "AI Data Storage", Risk_Level: RiskLevel.Moderate, Competitive_Position: "Oligopoly", Supply_Chain_Role: "System Integrator", Universal_Score: 81, Criticality: 7, Substitutability: "Moderate", Substitutability_Score: 60, Supply_Chain_Depth_Score: 40, SCSI: 95, PE_Ratio: -10.2, Forward_PE: 12.1, Revenue_Growth_YoY: -2.3, Debt_to_Equity: 1.2, Graham_Score: 4, ESG_Score: 77, Psych_Score: 65, Buy_Rank: 28, Probability_Of_Success: 72, Geopolitical_Risk: GeopoliticalRiskLevel.Medium, Geopolitical_Risk_Score: 40, Geopolitical_Notes: "Significant operations in Asia make it susceptible to regional supply chain issues and geopolitical trade tensions." },
  { Company: "Caterpillar", Ticker: "CAT", Exchange: "NYSE", Current_Price_USD: 329.2, Market_Cap_B: 165, YTD_Performance: 11.2, logoUrl: "https://logo.clearbit.com/caterpillar.com", Country: "USA", isBlueChip: false, Shares_Outstanding_M: 500, Float_Percent: 99, Category: "Power & Cooling", Sub_Category: "Backup Generators", Product_Component: "Diesel Generators", Universal_Presence: "Yes", Investment_Tier: InvestmentTier.OnRadar, Geographic_Presence: "Global", Recent_Contracts_2024_2025: "N/A", Growth_Driver: "Data Center Power Redundancy", Risk_Level: RiskLevel.Conservative, Competitive_Position: "Market Leader", Supply_Chain_Role: "Critical Infrastructure", Universal_Score: 85, Criticality: 8, Substitutability: "Difficult", Substitutability_Score: 30, Supply_Chain_Depth_Score: 40, SCSI: 170, PE_Ratio: 15.3, Forward_PE: 14.8, Revenue_Growth_YoY: 0.8, Debt_to_Equity: 1.8, Graham_Score: 7, ESG_Score: 70, Psych_Score: 66, Buy_Rank: 29, Probability_Of_Success: 84, Geopolitical_Risk: GeopoliticalRiskLevel.Low, Geopolitical_Risk_Score: 20, Geopolitical_Notes: "Iconic US brand with a diverse global sales network, reducing dependency on any single market." },
  { Company: "Cummins", Ticker: "CMI", Exchange: "NYSE", Current_Price_USD: 272.4, Market_Cap_B: 37, YTD_Performance: 13.3, logoUrl: "https://logo.clearbit.com/cummins.com", Country: "USA", isBlueChip: false, Shares_Outstanding_M: 136, Float_Percent: 99, Category: "Power & Cooling", Sub_Category: "Backup Generators", Product_Component: "Diesel Generators", Universal_Presence: "Yes", Investment_Tier: InvestmentTier.OnRadar, Geographic_Presence: "Global", Recent_Contracts_2024_2025: "N/A", Growth_Driver: "Hyperscale Backup Power", Risk_Level: RiskLevel.Conservative, Competitive_Position: "Market Leader", Supply_Chain_Role: "Critical Infrastructure", Universal_Score: 84, Criticality: 8, Substitutability: "Difficult", Substitutability_Score: 30, Supply_Chain_Depth_Score: 40, SCSI: 160, PE_Ratio: 14.1, Forward_PE: 13.5, Revenue_Growth_YoY: 7.5, Debt_to_Equity: 0.41, Graham_Score: 8, ESG_Score: 72, Psych_Score: 65, Buy_Rank: 30, Probability_Of_Success: 83, Geopolitical_Risk: GeopoliticalRiskLevel.Low, Geopolitical_Risk_Score: 25, Geopolitical_Notes: "US-based with significant international sales; somewhat exposed to global economic cycles and trade policies." },
  {
    Company: "Cadence Design Systems",
    Ticker: "CDNS",
    Exchange: "NASDAQ",
    Current_Price_USD: 310.5,
    Market_Cap_B: 85,
    Shares_Outstanding_M: 273,
    Float_Percent: 99,
    Category: "Software",
    Sub_Category: "EDA Software",
    Product_Component: "Electronic Design Automation Tools",
    Universal_Presence: "Yes - Foundation for all chip design",
    Investment_Tier: InvestmentTier.HighConviction,
    Geographic_Presence: "Global",
    Recent_Contracts_2024_2025: "Partnerships with all major foundries and fabless designers",
    Growth_Driver: "Increasing chip complexity and AI-driven design needs",
    Risk_Level: RiskLevel.Moderate,
    Competitive_Position: "Oligopoly",
    Supply_Chain_Role: "Critical Design Software",
    Universal_Score: 94,
    Criticality: 10,
    Substitutability: "Impossible",
    YTD_Performance: 15.2,
    logoUrl: "https://logo.clearbit.com/cadence.com",
    Country: "USA",
    Substitutability_Score: 10,
    Supply_Chain_Depth_Score: 10,
    SCSI: 350,
    ESG_Score: 82,
    PE_Ratio: 75.3,
    Forward_PE: 50.1,
    Revenue_Growth_YoY: 12.5,
    Debt_to_Equity: 0.1,
    isBlueChip: true,
    Graham_Score: 3,
    Psych_Score: 80,
    Buy_Rank: 31,
    Probability_Of_Success: 92,
    Geopolitical_Risk: GeopoliticalRiskLevel.Low,
    Geopolitical_Risk_Score: 10,
    Geopolitical_Notes: "Software is less susceptible to physical supply chain disruptions. Some risk from operating in China."
  },
  {
    Company: "Synopsys",
    Ticker: "SNPS",
    Exchange: "NASDAQ",
    Current_Price_USD: 590.8,
    Market_Cap_B: 90,
    Shares_Outstanding_M: 152,
    Float_Percent: 99,
    Category: "Software",
    Sub_Category: "EDA Software",
    Product_Component: "Electronic Design Automation Tools",
    Universal_Presence: "Yes - Foundation for all chip design",
    Investment_Tier: InvestmentTier.HighConviction,
    Geographic_Presence: "Global",
    Recent_Contracts_2024_2025: "Deep integration with AI chip designers",
    Growth_Driver: "AI acceleration in silicon design workflows",
    Risk_Level: RiskLevel.Moderate,
    Competitive_Position: "Oligopoly",
    Supply_Chain_Role: "Critical Design Software",
    Universal_Score: 94,
    Criticality: 10,
    Substitutability: "Impossible",
    YTD_Performance: 18.9,
    logoUrl: "https://logo.clearbit.com/synopsys.com",
    Country: "USA",
    Substitutability_Score: 10,
    Supply_Chain_Depth_Score: 10,
    SCSI: 345,
    ESG_Score: 84,
    PE_Ratio: 68.1,
    Forward_PE: 48.5,
    Revenue_Growth_YoY: 15.1,
    Debt_to_Equity: 0.2,
    isBlueChip: true,
    Graham_Score: 3,
    Psych_Score: 81,
    Buy_Rank: 32,
    Probability_Of_Success: 91,
    Geopolitical_Risk: GeopoliticalRiskLevel.Low,
    Geopolitical_Risk_Score: 10,
    Geopolitical_Notes: "As a software provider, insulated from direct manufacturing risks. Faces some regulatory risk regarding China."
  },
  {
    Company: "Applied Materials",
    Ticker: "AMAT",
    Exchange: "NASDAQ",
    Current_Price_USD: 235.6,
    Market_Cap_B: 195,
    Shares_Outstanding_M: 827,
    Float_Percent: 99,
    Category: "Semiconductors",
    Sub_Category: "Wafer Fab Equipment",
    Product_Component: "Deposition, Etch, Inspection",
    Universal_Presence: "Yes - Used in every fab worldwide",
    Investment_Tier: InvestmentTier.HighConviction,
    Geographic_Presence: "Global",
    Recent_Contracts_2024_2025: "Key supplier for GAA transition equipment",
    Growth_Driver: "Increasing capital intensity of advanced nodes",
    Risk_Level: RiskLevel.Moderate,
    Competitive_Position: "Market Leader",
    Supply_Chain_Role: "Critical Equipment Supplier",
    Universal_Score: 91,
    Criticality: 9,
    Substitutability: "Difficult",
    YTD_Performance: 45.3,
    logoUrl: "https://logo.clearbit.com/amat.com",
    Country: "USA",
    Substitutability_Score: 30,
    Supply_Chain_Depth_Score: 70,
    SCSI: 280,
    ESG_Score: 80,
    PE_Ratio: 28.2,
    Forward_PE: 22.1,
    Revenue_Growth_YoY: 0.5,
    Debt_to_Equity: 0.4,
    isBlueChip: true,
    Graham_Score: 6,
    Psych_Score: 79,
    Buy_Rank: 33,
    Probability_Of_Success: 88,
    Geopolitical_Risk: GeopoliticalRiskLevel.Medium,
    Geopolitical_Risk_Score: 50,
    Geopolitical_Notes: "Subject to US export controls and has significant exposure to customers in geopolitical hotspots like Taiwan and China."
  },
  {
    Company: "Lam Research",
    Ticker: "LRCX",
    Exchange: "NASDAQ",
    Current_Price_USD: 1050.2,
    Market_Cap_B: 135,
    Shares_Outstanding_M: 128,
    Float_Percent: 99,
    Category: "Semiconductors",
    Sub_Category: "Wafer Fab Equipment",
    Product_Component: "Etch and Deposition Systems",
    Universal_Presence: "Yes - Leader in etch for advanced nodes",
    Investment_Tier: InvestmentTier.HighConviction,
    Geographic_Presence: "Global",
    Recent_Contracts_2024_2025: "High demand for HBM manufacturing tools",
    Growth_Driver: "3D NAND and DRAM technology transitions",
    Risk_Level: RiskLevel.Moderate,
    Competitive_Position: "Market Leader",
    Supply_Chain_Role: "Critical Equipment Supplier",
    Universal_Score: 90,
    Criticality: 9,
    Substitutability: "Difficult",
    YTD_Performance: 33.8,
    logoUrl: "https://logo.clearbit.com/lamresearch.com",
    Country: "USA",
    Substitutability_Score: 30,
    Supply_Chain_Depth_Score: 70,
    SCSI: 275,
    ESG_Score: 78,
    PE_Ratio: 33.5,
    Forward_PE: 25.9,
    Revenue_Growth_YoY: -5.2,
    Debt_to_Equity: 0.5,
    isBlueChip: true,
    Graham_Score: 6,
    Psych_Score: 77,
    Buy_Rank: 34,
    Probability_Of_Success: 87,
    Geopolitical_Risk: GeopoliticalRiskLevel.Medium,
    Geopolitical_Risk_Score: 50,
    Geopolitical_Notes: "Faces similar risks to AMAT regarding export controls and customer concentration in politically sensitive regions."
  },
  {
    Company: "Corning",
    Ticker: "GLW",
    Exchange: "NYSE",
    Current_Price_USD: 39.5,
    Market_Cap_B: 33,
    Shares_Outstanding_M: 835,
    Float_Percent: 99,
    Category: "Interconnects",
    Sub_Category: "Fiber Optics",
    Product_Component: "Optical Fiber, Specialty Glass",
    Universal_Presence: "Yes - Major provider of optical fiber",
    Investment_Tier: InvestmentTier.OnRadar,
    Geographic_Presence: "Global",
    Recent_Contracts_2024_2025: "Increased fiber deployments for AI data center interconnects",
    Growth_Driver: "Data center bandwidth requirements",
    Risk_Level: RiskLevel.Conservative,
    Competitive_Position: "Market Leader",
    Supply_Chain_Role: "Core Component Supplier",
    Universal_Score: 86,
    Criticality: 8,
    Substitutability: "Moderate",
    YTD_Performance: 30.1,
    logoUrl: "https://logo.clearbit.com/corning.com",
    Country: "USA",
    Substitutability_Score: 50,
    Supply_Chain_Depth_Score: 70,
    SCSI: 160,
    ESG_Score: 81,
    PE_Ratio: 35.1,
    Forward_PE: 18.2,
    Revenue_Growth_YoY: 1.8,
    Debt_to_Equity: 0.6,
    isBlueChip: false,
    Graham_Score: 7,
    Psych_Score: 68,
    Buy_Rank: 35,
    Probability_Of_Success: 80,
    Geopolitical_Risk: GeopoliticalRiskLevel.Low,
    Geopolitical_Risk_Score: 20,
    Geopolitical_Notes: "Well-diversified, mature US company with global reach but less concentration in high-risk geopolitical zones."
  },
  {
    Company: "Marvell Technology",
    Ticker: "MRVL",
    Exchange: "NASDAQ",
    Current_Price_USD: 72.8,
    Market_Cap_B: 62,
    Shares_Outstanding_M: 851,
    Float_Percent: 98,
    Category: "Networking",
    Sub_Category: "Custom Silicon",
    Product_Component: "Custom ASICs, DPUs, Networking chips",
    Universal_Presence: "Yes - Key enabler for custom cloud silicon",
    Investment_Tier: InvestmentTier.OnRadar,
    Geographic_Presence: "Global",
    Recent_Contracts_2024_2025: "Major custom silicon wins with cloud providers",
    Growth_Driver: "AI Accelerators and Cloud Infrastructure",
    Risk_Level: RiskLevel.Aggressive,
    Competitive_Position: "Strong Niche Player",
    Supply_Chain_Role: "Component Supplier",
    Universal_Score: 89,
    Criticality: 8,
    Substitutability: "Difficult",
    YTD_Performance: 20.5,
    logoUrl: "https://logo.clearbit.com/marvell.com",
    Country: "USA",
    Substitutability_Score: 35,
    Supply_Chain_Depth_Score: 70,
    SCSI: 200,
    ESG_Score: 70,
    PE_Ratio: -150.2,
    Forward_PE: 30.5,
    Revenue_Growth_YoY: -12.3,
    Debt_to_Equity: 0.25,
    isBlueChip: false,
    Graham_Score: 2,
    Psych_Score: 83,
    Buy_Rank: 36,
    Probability_Of_Success: 78,
    Geopolitical_Risk: GeopoliticalRiskLevel.Medium,
    Geopolitical_Risk_Score: 45,
    Geopolitical_Notes: "Fabless model creates dependency on Asian foundries like TSMC, inheriting their geopolitical risks."
  },
  {
    Company: "Delta Electronics",
    Ticker: "2308.TW",
    Exchange: "Taiwan",
    Current_Price_USD: 11.5,
    Market_Cap_B: 30,
    Shares_Outstanding_M: 2598,
    Float_Percent: 75,
    Category: "Power & Cooling",
    Sub_Category: "Power Supplies",
    Product_Component: "Server PSUs, DC-DC converters, Fans",
    Universal_Presence: "Yes - World's largest provider of switching power supplies",
    Investment_Tier: InvestmentTier.HighConviction,
    Geographic_Presence: "Global",
    Recent_Contracts_2024_2025: "Key supplier for liquid cooling power components",
    Growth_Driver: "Higher power density in AI servers",
    Risk_Level: RiskLevel.Moderate,
    Competitive_Position: "Market Leader",
    Supply_Chain_Role: "Universal Component",
    Universal_Score: 92,
    Criticality: 9,
    Substitutability: "Moderate",
    YTD_Performance: 25.7,
    logoUrl: "https://logo.clearbit.com/deltaww.com",
    Country: "Taiwan",
    Substitutability_Score: 40,
    Supply_Chain_Depth_Score: 70,
    SCSI: 250,
    ESG_Score: 88,
    PE_Ratio: 25.8,
    Forward_PE: 22.1,
    Revenue_Growth_YoY: 8.9,
    Debt_to_Equity: 0.3,
    isBlueChip: false,
    Graham_Score: 7,
    Psych_Score: 75,
    Buy_Rank: 37,
    Probability_Of_Success: 86,
    Geopolitical_Risk: GeopoliticalRiskLevel.VeryHigh,
    Geopolitical_Risk_Score: 85,
    Geopolitical_Notes: "Taiwanese base of operations exposes the company to significant cross-strait geopolitical risks."
  },
  {
    Company: "Schneider Electric",
    Ticker: "SU.PA",
    Exchange: "Euronext Paris",
    Current_Price_USD: 245.2,
    Market_Cap_B: 135,
    Shares_Outstanding_M: 550,
    Float_Percent: 90,
    Category: "Power & Cooling",
    Sub_Category: "UPS, Switchgear",
    Product_Component: "UPS Systems, PDUs, Cooling (APC brand)",
    Universal_Presence: "Yes - Global leader in energy management",
    Investment_Tier: InvestmentTier.HighConviction,
    Geographic_Presence: "Global",
    Recent_Contracts_2024_2025: "Expanding data center solutions for AI workloads",
    Growth_Driver: "Data center electrification and efficiency",
    Risk_Level: RiskLevel.Conservative,
    Competitive_Position: "Market Leader",
    Supply_Chain_Role: "Critical Infrastructure",
    Universal_Score: 90,
    Criticality: 9,
    Substitutability: "Moderate",
    YTD_Performance: 22.1,
    logoUrl: "https://logo.clearbit.com/se.com",
    Country: "France",
    Substitutability_Score: 60,
    Supply_Chain_Depth_Score: 40,
    SCSI: 215,
    ESG_Score: 90,
    PE_Ratio: 26.3,
    Forward_PE: 23.4,
    Revenue_Growth_YoY: 10.5,
    Debt_to_Equity: 0.5,
    isBlueChip: true,
    Graham_Score: 7,
    Psych_Score: 72,
    Buy_Rank: 38,
    Probability_Of_Success: 89,
    Geopolitical_Risk: GeopoliticalRiskLevel.Low,
    Geopolitical_Risk_Score: 15,
    Geopolitical_Notes: "French multinational with a diversified global presence, limiting exposure to single-country risk."
  },
  {
    Company: "Generac",
    Ticker: "GNRC",
    Exchange: "NYSE",
    Current_Price_USD: 130.8,
    Market_Cap_B: 8,
    Shares_Outstanding_M: 61,
    Float_Percent: 99,
    Category: "Power & Cooling",
    Sub_Category: "Backup Generators",
    Product_Component: "Natural Gas & Diesel Generators",
    Universal_Presence: "Growing - Expanding into industrial/DC market",
    Investment_Tier: InvestmentTier.OnRadar,
    Geographic_Presence: "North America",
    Recent_Contracts_2024_2025: "New product lines for data center applications",
    Growth_Driver: "Need for reliable backup power for AI",
    Risk_Level: RiskLevel.Aggressive,
    Competitive_Position: "Challenger",
    Supply_Chain_Role: "Critical Infrastructure",
    Universal_Score: 80,
    Criticality: 7,
    Substitutability: "Moderate",
    YTD_Performance: -5.6,
    logoUrl: "https://logo.clearbit.com/generac.com",
    Country: "USA",
    Substitutability_Score: 50,
    Supply_Chain_Depth_Score: 40,
    SCSI: 100,
    ESG_Score: 65,
    PE_Ratio: 40.2,
    Forward_PE: 16.1,
    Revenue_Growth_YoY: -10.8,
    Debt_to_Equity: 0.7,
    isBlueChip: false,
    Graham_Score: 5,
    Psych_Score: 55,
    Buy_Rank: 39,
    Probability_Of_Success: 71,
    Geopolitical_Risk: GeopoliticalRiskLevel.Low,
    Geopolitical_Risk_Score: 10,
    Geopolitical_Notes: "Primarily focused on the North American market, providing strong insulation from international geopolitical events."
  },
  {
    Company: "Shin-Etsu Chemical",
    Ticker: "4063.T",
    Exchange: "Tokyo",
    Current_Price_USD: 38.5,
    Market_Cap_B: 78,
    Shares_Outstanding_M: 2025,
    Float_Percent: 80,
    Category: "Semiconductors",
    Sub_Category: "Silicon Wafers",
    Product_Component: "300mm Silicon Wafers",
    Universal_Presence: "Yes - World's largest wafer manufacturer",
    Investment_Tier: InvestmentTier.MustBuy,
    Geographic_Presence: "Global",
    Recent_Contracts_2024_2025: "Dominant supplier to all major foundries",
    Growth_Driver: "Foundation of entire semiconductor industry",
    Risk_Level: RiskLevel.Moderate,
    Competitive_Position: "Market Leader",
    Supply_Chain_Role: "Raw Material Supplier",
    Universal_Score: 92,
    Criticality: 9,
    Substitutability: "Difficult",
    YTD_Performance: 12.3,
    logoUrl: "https://logo.clearbit.com/shinetsu.co.jp",
    Country: "Japan",
    Substitutability_Score: 30,
    Supply_Chain_Depth_Score: 100,
    SCSI: 310,
    ESG_Score: 75,
    PE_Ratio: 20.1,
    Forward_PE: 18.5,
    Revenue_Growth_YoY: -8.1,
    Debt_to_Equity: 0.1,
    isBlueChip: false,
    Graham_Score: 8,
    Psych_Score: 70,
    Buy_Rank: 40,
    Probability_Of_Success: 85,
    Geopolitical_Risk: GeopoliticalRiskLevel.Medium,
    Geopolitical_Risk_Score: 30,
    Geopolitical_Notes: "Japanese base provides stability, but proximity to regional tensions in Asia poses a moderate risk."
  },
  {
    Company: "Entegris",
    Ticker: "ENTG",
    Exchange: "NASDAQ",
    Current_Price_USD: 135.2,
    Market_Cap_B: 20,
    Shares_Outstanding_M: 150,
    Float_Percent: 99,
    Category: "Semiconductors",
    Sub_Category: "Specialty Materials",
    Product_Component: "Filters, Purifiers, Specialty Chemicals",
    Universal_Presence: "Yes - Critical for advanced node purity",
    Investment_Tier: InvestmentTier.OnRadar,
    Geographic_Presence: "Global",
    Recent_Contracts_2024_2025: "Materials solutions for 2nm and below",
    Growth_Driver: "Increasing material complexity in chipmaking",
    Risk_Level: RiskLevel.Moderate,
    Competitive_Position: "Niche Leader",
    Supply_Chain_Role: "Specialty Material",
    Universal_Score: 88,
    Criticality: 9,
    Substitutability: "Difficult",
    YTD_Performance: 30.2,
    logoUrl: "https://logo.clearbit.com/entegris.com",
    Country: "USA",
    Substitutability_Score: 25,
    Supply_Chain_Depth_Score: 100,
    SCSI: 230,
    ESG_Score: 81,
    PE_Ratio: 70.5,
    Forward_PE: 32.1,
    Revenue_Growth_YoY: 5.5,
    Debt_to_Equity: 1.5,
    isBlueChip: false,
    Graham_Score: 4,
    Psych_Score: 76,
    Buy_Rank: 41,
    Probability_Of_Success: 82,
    Geopolitical_Risk: GeopoliticalRiskLevel.Low,
    Geopolitical_Risk_Score: 25,
    Geopolitical_Notes: "US-based specialty provider, but sales are global and can be impacted by customer-side geopolitical issues (e.g., fabs in Taiwan)."
  },
  {
    Company: "DuPont",
    Ticker: "DD",
    Exchange: "NYSE",
    Current_Price_USD: 80.1,
    Market_Cap_B: 34,
    Shares_Outstanding_M: 425,
    Float_Percent: 99,
    Category: "Raw Materials",
    Sub_Category: "Specialty Chemicals",
    Product_Component: "Adhesives, Polymers, Films for PCBs",
    Universal_Presence: "Yes - Materials used in countless electronic components",
    Investment_Tier: InvestmentTier.OnRadar,
    Geographic_Presence: "Global",
    Recent_Contracts_2024_2025: "Developing next-gen materials for high-speed interconnects",
    Growth_Driver: "Advanced packaging and electronics",
    Risk_Level: RiskLevel.Conservative,
    Competitive_Position: "Established Leader",
    Supply_Chain_Role: "Specialty Material",
    Universal_Score: 85,
    Criticality: 8,
    Substitutability: "Moderate",
    YTD_Performance: 8.5,
    logoUrl: "https://logo.clearbit.com/dupont.com",
    Country: "USA",
    Substitutability_Score: 50,
    Supply_Chain_Depth_Score: 100,
    SCSI: 150,
    ESG_Score: 83,
    PE_Ratio: 12.1,
    Forward_PE: 15.2,
    Revenue_Growth_YoY: -7.3,
    Debt_to_Equity: 0.4,
    isBlueChip: true,
    Graham_Score: 8,
    Psych_Score: 64,
    Buy_Rank: 42,
    Probability_Of_Success: 79,
    Geopolitical_Risk: GeopoliticalRiskLevel.Low,
    Geopolitical_Risk_Score: 20,
    Geopolitical_Notes: "A diversified US chemical giant with a global footprint that provides resilience against regional disruptions."
  },
  {
    Company: "Dell Technologies",
    Ticker: "DELL",
    Exchange: "NYSE",
    Current_Price_USD: 140.5,
    Market_Cap_B: 98,
    Shares_Outstanding_M: 697,
    Float_Percent: 35,
    Category: "Hardware",
    Sub_Category: "AI Servers",
    Product_Component: "PowerEdge Servers with NVIDIA GPUs",
    Universal_Presence: "Yes - Top 3 server vendor globally",
    Investment_Tier: InvestmentTier.OnRadar,
    Geographic_Presence: "Global",
    Recent_Contracts_2024_2025: "Expanding AI server portfolio for enterprise",
    Growth_Driver: "Enterprise adoption of GenAI",
    Risk_Level: RiskLevel.Moderate,
    Competitive_Position: "Market Leader",
    Supply_Chain_Role: "System Integrator",
    Universal_Score: 91,
    Criticality: 8,
    Substitutability: "Moderate",
    YTD_Performance: 85.6,
    logoUrl: "https://logo.clearbit.com/dell.com",
    Country: "USA",
    Substitutability_Score: 60,
    Supply_Chain_Depth_Score: 40,
    SCSI: 80,
    ESG_Score: 85,
    PE_Ratio: 30.1,
    Forward_PE: 15.8,
    Revenue_Growth_YoY: 6.3,
    Debt_to_Equity: 5.8,
    isBlueChip: true,
    Graham_Score: 5,
    Psych_Score: 91,
    Buy_Rank: 43,
    Probability_Of_Success: 80,
    Geopolitical_Risk: GeopoliticalRiskLevel.Medium,
    Geopolitical_Risk_Score: 40,
    Geopolitical_Notes: "Relies on a complex global supply chain, with significant manufacturing and component sourcing in Asia."
  },
  {
    Company: "Quanta Computer",
    Ticker: "2382.TW",
    Exchange: "Taiwan",
    Current_Price_USD: 9.2,
    Market_Cap_B: 35,
    Shares_Outstanding_M: 3850,
    Float_Percent: 70,
    Category: "Hardware",
    Sub_Category: "AI Servers (ODM)",
    Product_Component: "Rack-scale systems for hyperscalers",
    Universal_Presence: "Yes - Major ODM for Meta, Google",
    Investment_Tier: InvestmentTier.OnRadar,
    Geographic_Presence: "Global",
    Recent_Contracts_2024_2025: "High-volume production of next-gen AI servers",
    Growth_Driver: "Direct supplier to cloud giants",
    Risk_Level: RiskLevel.Moderate,
    Competitive_Position: "Market Leader",
    Supply_Chain_Role: "System Integrator",
    Universal_Score: 87,
    Criticality: 8,
    Substitutability: "Moderate",
    YTD_Performance: 40.1,
    logoUrl: "https://logo.clearbit.com/quantatw.com",
    Country: "Taiwan",
    Substitutability_Score: 50,
    Supply_Chain_Depth_Score: 40,
    SCSI: 75,
    ESG_Score: 78,
    PE_Ratio: 22.5,
    Forward_PE: 18.3,
    Revenue_Growth_YoY: 15.2,
    Debt_to_Equity: 0.9,
    isBlueChip: false,
    Graham_Score: 6,
    Psych_Score: 80,
    Buy_Rank: 44,
    Probability_Of_Success: 76,
    Geopolitical_Risk: GeopoliticalRiskLevel.VeryHigh,
    Geopolitical_Risk_Score: 85,
    Geopolitical_Notes: "As a Taiwan-based ODM, it faces direct geopolitical risks and supply chain concentration issues."
  },
  {
    Company: "Wiwynn",
    Ticker: "6669.TW",
    Exchange: "Taiwan",
    Current_Price_USD: 85.3,
    Market_Cap_B: 15,
    Shares_Outstanding_M: 175,
    Float_Percent: 40,
    Category: "Hardware",
    Sub_Category: "AI Servers (ODM)",
    Product_Component: "Cloud & AI server solutions",
    Universal_Presence: "Yes - Key supplier to Microsoft, Meta",
    Investment_Tier: InvestmentTier.OnRadar,
    Geographic_Presence: "Global",
    Recent_Contracts_2024_2025: "Specialized in high-density AI rack solutions",
    Growth_Driver: "Hyperscale data center buildout",
    Risk_Level: RiskLevel.Aggressive,
    Competitive_Position: "Niche Leader",
    Supply_Chain_Role: "System Integrator",
    Universal_Score: 89,
    Criticality: 8,
    Substitutability: "Difficult",
    YTD_Performance: 55.2,
    logoUrl: "https://logo.clearbit.com/wiwynn.com",
    Country: "Taiwan",
    Substitutability_Score: 40,
    Supply_Chain_Depth_Score: 40,
    SCSI: 85,
    ESG_Score: 75,
    PE_Ratio: 25.1,
    Forward_PE: 20.4,
    Revenue_Growth_YoY: 28.3,
    Debt_to_Equity: 1.1,
    isBlueChip: false,
    Graham_Score: 5,
    Psych_Score: 85,
    Buy_Rank: 45,
    Probability_Of_Success: 77,
    Geopolitical_Risk: GeopoliticalRiskLevel.VeryHigh,
    Geopolitical_Risk_Score: 85,
    Geopolitical_Notes: "A spin-off of Wistron, this Taiwan-based ODM carries the same high level of geopolitical risk."
  }
];

export const dataCenterVisualizerConfig = {
    imageUrl: 'https://images.unsplash.com/photo-1580577662843-5226a3a7b6c4?q=80&w=2070&auto=format&fit=crop',
    hotspots: [
        {
            id: 'power-cooling',
            title: 'Power & Cooling Infrastructure',
            description: 'The foundation of any data center. Includes UPS, PDUs, switchgear, backup generators, and advanced liquid/air cooling systems.',
            coordinates: { top: '55%', left: '10%', width: '30%', height: '35%' },
            associatedCategories: ['Power & Cooling'],
        },
        {
            id: 'compute',
            title: 'Compute & Networking Racks',
            description: 'Houses high-density servers, GPUs, and high-speed networking switches that power AI workloads. This is the core of the data center.',
            coordinates: { top: '25%', left: '45%', width: '40%', height: '50%' },
            associatedCategories: ['Semiconductors', 'Hardware', 'Networking', 'Components'],
        },
        {
            id: 'cabling',
            title: 'Interconnects & Cabling',
            description: 'High-speed fiber optic and copper cabling that forms the data center\'s nervous system, connecting all components.',
            coordinates: { top: '75%', left: '50%', width: '35%', height: '15%' },
            associatedCategories: ['Interconnects'],
        },
        {
            id: 'construction',
            title: 'Physical Building & Materials',
            description: 'The structural shell, including steel frames, raised flooring, cable trays, and insulated panels.',
            coordinates: { top: '5%', left: '5%', width: '90%', height: '90%' },
            associatedCategories: ['Construction'],
        },
        {
            id: 'materials',
            title: 'Raw & Specialty Materials',
            description: 'Fundamental resources like copper, rare earth elements, silicon wafers, and specialty chemicals that are the building blocks of all other components.',
            coordinates: { top: '5%', left: '75%', width: '20%', height: '20%' },
            associatedCategories: ['Raw Materials'],
        },
         {
            id: 'software',
            title: 'Software & Design',
            description: 'The software layer, including Electronic Design Automation (EDA) tools used to design the chips that power the entire infrastructure.',
            coordinates: { top: '5%', left: '5%', width: '20%', height: '20%' },
            associatedCategories: ['Software'],
        }
    ] as Hotspot[],
};