import { Company, InvestmentTier, RiskLevel } from './types';

// This data is derived from the user-provided CSV and enriched with
// quantitative metrics as defined in the BI and Advanced Strategy documents.
export const companiesData: Company[] = [
  {
    Company: "TSMC",
    Ticker: "TSM",
    Exchange: "NYSE",
    Current_Price_USD: 195.92,
    Market_Cap_B: 1490,
    Shares_Outstanding_M: 25900,
    Float_Percent: 80,
    Category: "Semiconductors",
    Sub_Category: "Semiconductor Fabrication",
    Product_Component: "4nm-2nm AI Chip Manufacturing",
    Universal_Presence: "Yes - Manufactures 90%+ of all AI chips",
    Investment_Tier: InvestmentTier.MustBuy,
    Geographic_Presence: "Global: Taiwan (primary), Arizona (emerging)",
    Recent_Contracts_2024_2025: "NVIDIA Blackwell, AMD MI300, Apple, Broadcom - $33B Q3 2025 revenue",
    Growth_Driver: "Only advanced AI chip foundry",
    Risk_Level: RiskLevel.High,
    Competitive_Position: "Monopoly Position",
    Supply_Chain_Role: "Critical Bottleneck",
    Universal_Score: 100,
    Criticality: 10,
    Substitutability: "Impossible",
    YTD_Performance: 68.3,
    logoUrl: "https://logo.clearbit.com/tsmc.com",
    Country: "Taiwan",
    Substitutability_Score: 0,
    Supply_Chain_Depth_Score: 70,
    SCSI: 420,
    ESG_Score: 85,
    PE_Ratio: 34.2,
    Forward_PE: 25.1,
    Revenue_Growth_YoY: 16.5,
    Debt_to_Equity: 0.45,
    Graham_Score: 7,
    isBlueChip: true,
  },
  {
    Company: "ASML Holding",
    Ticker: "ASML",
    Exchange: "NASDAQ",
    Current_Price_USD: 1025.78,
    Market_Cap_B: 408,
    Shares_Outstanding_M: 398,
    Float_Percent: 98,
    Category: "Semiconductors",
    Sub_Category: "Lithography Equipment",
    Product_Component: "EUV Lithography Machines",
    Universal_Presence: "Yes - Monopoly supplier to all advanced fabs",
    Investment_Tier: InvestmentTier.MustBuy,
    Geographic_Presence: "Global: Netherlands (HQ)",
    Recent_Contracts_2024_2025: "Exclusive supplier to TSMC, Intel, Samsung for advanced nodes",
    Growth_Driver: "Gate-All-Around (GAA) transition requires EUV",
    Risk_Level: RiskLevel.Moderate,
    Competitive_Position: "Monopoly",
    Supply_Chain_Role: "Critical Equipment Supplier",
    Universal_Score: 99,
    Criticality: 10,
    Substitutability: "Impossible",
    YTD_Performance: 38.8,
    logoUrl: "https://logo.clearbit.com/asml.com",
    Country: "Netherlands",
    Substitutability_Score: 0,
    Supply_Chain_Depth_Score: 70,
    SCSI: 450,
    ESG_Score: 89,
    PE_Ratio: 52.9,
    Forward_PE: 41.5,
    Revenue_Growth_YoY: -21.6,
    Debt_to_Equity: 0.28,
    Graham_Score: 8,
    isBlueChip: true,
  },
  {
    Company: "SK Hynix",
    Ticker: "000660.KS",
    Exchange: "Korea",
    Current_Price_USD: 148,
    Market_Cap_B: 102,
    Shares_Outstanding_M: 728,
    Float_Percent: 85,
    Category: "Semiconductors",
    Sub_Category: "HBM Memory",
    Product_Component: "HBM3E, HBM4 - 62% Market Share",
    Universal_Presence: "Yes - Integrated on every NVIDIA GPU",
    Investment_Tier: InvestmentTier.MustBuy,
    Geographic_Presence: "Global: Korea (primary), China",
    Recent_Contracts_2024_2025: "Sold out through 2026, NVIDIA exclusive supplier",
    Growth_Driver: "Controls AI memory bottleneck",
    Risk_Level: RiskLevel.Moderate,
    Competitive_Position: "Market Leader",
    Supply_Chain_Role: "Critical Bottleneck",
    Universal_Score: 98,
    Criticality: 10,
    Substitutability: "Impossible",
    YTD_Performance: 55.1,
    logoUrl: "https://logo.clearbit.com/skhynix.com",
    Country: "Korea",
    Substitutability_Score: 5,
    Supply_Chain_Depth_Score: 70,
    SCSI: 505,
    ESG_Score: 82,
    PE_Ratio: -20.5,
    Forward_PE: 8.5,
    Revenue_Growth_YoY: 144,
    Debt_to_Equity: 0.65,
    Graham_Score: 7,
    isBlueChip: false,
  },
  {
    Company: "Freeport-McMoRan",
    Ticker: "FCX",
    Exchange: "NYSE",
    Current_Price_USD: 43.82,
    Market_Cap_B: 62,
    Shares_Outstanding_M: 1420,
    Float_Percent: 99,
    Category: "Raw Materials",
    Sub_Category: "Copper Mining",
    Product_Component: "Copper Cathodes for All Wiring/PCBs",
    Universal_Presence: "Yes - 5-10 tons per MW capacity",
    Investment_Tier: InvestmentTier.MustBuy,
    Geographic_Presence: "Global: Americas, Indonesia",
    Recent_Contracts_2024_2025: "Copper shortage warning 6M tons by 2035",
    Growth_Driver: "Every cable, PCB, transformer uses copper",
    Risk_Level: RiskLevel.Moderate,
    Competitive_Position: "Major Producer",
    Supply_Chain_Role: "Raw Material Supplier",
    Universal_Score: 97,
    Criticality: 10,
    Substitutability: "Difficult",
    YTD_Performance: 28.2,
    logoUrl: "https://logo.clearbit.com/fcx.com",
    Country: "USA",
    Substitutability_Score: 30,
    Supply_Chain_Depth_Score: 100,
    SCSI: 380,
    ESG_Score: 65,
    PE_Ratio: 22.1,
    Forward_PE: 15.8,
    Revenue_Growth_YoY: 5.6,
    Debt_to_Equity: 0.4,
    Graham_Score: 7,
    isBlueChip: false,
  },
  {
    Company: "Nucor",
    Ticker: "NUE",
    Exchange: "NYSE",
    Current_Price_USD: 158.3,
    Market_Cap_B: 38,
    Shares_Outstanding_M: 240,
    Float_Percent: 99,
    Category: "Construction",
    Sub_Category: "Structural Steel",
    Product_Component: "EAF Steel for Racks, Frames, Trays",
    Universal_Presence: "Yes - Every rack, frame, structural element",
    Investment_Tier: InvestmentTier.MustBuy,
    Geographic_Presence: "North America: 300+ facilities",
    Recent_Contracts_2024_2025: "Multi-billion contracts for hyperscale AI DCs",
    Growth_Driver: "Largest NA steel producer",
    Risk_Level: RiskLevel.Conservative,
    Competitive_Position: "Market Leader",
    Supply_Chain_Role: "Structural Material",
    Universal_Score: 97,
    Criticality: 9,
    Substitutability: "Moderate",
    YTD_Performance: 22,
    logoUrl: "https://logo.clearbit.com/nucor.com",
    Country: "USA",
    Substitutability_Score: 60,
    Supply_Chain_Depth_Score: 100,
    SCSI: 120,
    ESG_Score: 81,
    PE_Ratio: 10.5,
    Forward_PE: 10,
    Revenue_Growth_YoY: -15,
    Debt_to_Equity: 0.35,
    Graham_Score: 9,
    isBlueChip: false,
  },
   {
    Company: "Southern Copper",
    Ticker: "SCCO",
    Exchange: "NYSE",
    Current_Price_USD: 93.05,
    Market_Cap_B: 71.9,
    Shares_Outstanding_M: 773,
    Float_Percent: 88,
    Category: "Raw Materials",
    Sub_Category: "Copper Mining",
    Product_Component: "Copper Wire Rod, Cathodes",
    Universal_Presence: "Yes - All power distribution uses copper",
    Investment_Tier: InvestmentTier.MustBuy,
    Geographic_Presence: "Americas: Peru, Mexico",
    Recent_Contracts_2024_2025: "Tia Maria $1.8B expansion starting 2027",
    Growth_Driver: "42% Americas market share",
    Risk_Level: RiskLevel.Moderate,
    Competitive_Position: "Regional Leader",
    Supply_Chain_Role: "Raw Material Supplier",
    Universal_Score: 96,
    Criticality: 10,
    Substitutability: "Difficult",
    YTD_Performance: 31,
    logoUrl: "https://logo.clearbit.com/southerncoppercorp.com",
    Country: "Mexico",
    Substitutability_Score: 30,
    Supply_Chain_Depth_Score: 100,
    SCSI: 370,
    ESG_Score: 68,
    PE_Ratio: 30.2,
    Forward_PE: 24,
    Revenue_Growth_YoY: 8.1,
    Debt_to_Equity: 0.5,
    Graham_Score: 6,
    isBlueChip: false,
  },
  {
    Company: "MP Materials",
    Ticker: "MP",
    Exchange: "NYSE",
    Current_Price_USD: 28.35,
    Market_Cap_B: 12.36,
    Shares_Outstanding_M: 436,
    Float_Percent: 82,
    Category: "Raw Materials",
    Sub_Category: "Rare Earth Elements",
    Product_Component: "NdPr for Magnets in HDDs, Fans, Motors",
    Universal_Presence: "Yes - Every HDD, fan, motor has rare earth magnets",
    Investment_Tier: InvestmentTier.MustBuy,
    Geographic_Presence: "North America: California only US source",
    Recent_Contracts_2024_2025: "DoD multi-billion 10X Facility, Apple $500M investment",
    Growth_Driver: "Only US rare earth producer",
    Risk_Level: RiskLevel.High,
    Competitive_Position: "US Monopoly",
    Supply_Chain_Role: "Strategic Material",
    Universal_Score: 95,
    Criticality: 9,
    Substitutability: "Impossible",
    YTD_Performance: -10,
    logoUrl: "https://logo.clearbit.com/mpmaterials.com",
    Country: "USA",
    Substitutability_Score: 0,
    Supply_Chain_Depth_Score: 100,
    SCSI: 340,
    ESG_Score: 50,
    PE_Ratio: 55,
    Forward_PE: 30,
    Revenue_Growth_YoY: -35,
    Debt_to_Equity: 1.2,
    Graham_Score: 4,
    isBlueChip: false,
  },
  {
    Company: "Broadcom",
    Ticker: "AVGO",
    Exchange: "NASDAQ",
    Current_Price_USD: 167.5,
    Market_Cap_B: 1010,
    Shares_Outstanding_M: 6030,
    Float_Percent: 85,
    Category: "Networking",
    Sub_Category: "Switching Silicon",
    Product_Component: "Tomahawk 5/4 ASICs for Switches",
    Universal_Presence: "Yes - Powers Arista, Cisco, most DC switches",
    Investment_Tier: InvestmentTier.HighConviction,
    Geographic_Presence: "Global: Fabless design",
    Recent_Contracts_2024_2025: "51.2T switch capacity ASICs, custom AI accelerators",
    Growth_Driver: "Silicon behind most networking gear",
    Risk_Level: RiskLevel.Moderate,
    Competitive_Position: "Oligopoly",
    Supply_Chain_Role: "Component Supplier",
    Universal_Score: 94,
    Criticality: 10,
    Substitutability: "Difficult",
    YTD_Performance: 49.3,
    logoUrl: "https://logo.clearbit.com/broadcom.com",
    Country: "USA",
    Substitutability_Score: 25,
    Supply_Chain_Depth_Score: 70,
    SCSI: 320,
    ESG_Score: 68,
    PE_Ratio: 58.1,
    Forward_PE: 33.7,
    Revenue_Growth_YoY: 43,
    Debt_to_Equity: 1.05,
    Graham_Score: 6,
    isBlueChip: true,
  },
  {
    Company: "Amphenol",
    Ticker: "APH",
    Exchange: "NYSE",
    Current_Price_USD: 138.11,
    Market_Cap_B: 163.35,
    Shares_Outstanding_M: 1180,
    Float_Percent: 99,
    Category: "Interconnects",
    Sub_Category: "Connectors, Cables",
    Product_Component: "High-Frequency Interconnects, 400G/800G",
    Universal_Presence: "Yes - Every device uses Amphenol connectors",
    Investment_Tier: InvestmentTier.HighConviction,
    Geographic_Presence: "Global: 100+ countries",
    Recent_Contracts_2024_2025: "400G/800G adoption, +54% spike 2024",
    Growth_Driver: "Universal connector presence",
    Risk_Level: RiskLevel.Conservative,
    Competitive_Position: "Market Leader",
    Supply_Chain_Role: "Universal Component",
    Universal_Score: 94,
    Criticality: 10,
    Substitutability: "Difficult",
    YTD_Performance: 54,
    logoUrl: "https://logo.clearbit.com/amphenol.com",
    Country: "USA",
    Substitutability_Score: 30,
    Supply_Chain_Depth_Score: 70,
    SCSI: 260,
    ESG_Score: 74,
    PE_Ratio: 30.5,
    Forward_PE: 26.8,
    Revenue_Growth_YoY: 2.5,
    Debt_to_Equity: 0.5,
    Graham_Score: 6,
    isBlueChip: false,
  },
  {
    Company: "Vertiv",
    Ticker: "VRT",
    Exchange: "NYSE",
    Current_Price_USD: 118.5,
    Market_Cap_B: 45,
    Shares_Outstanding_M: 380,
    Float_Percent: 98,
    Category: "Power & Cooling",
    Sub_Category: "UPS, PDUs, Cooling",
    Product_Component: "Liebert UPS, Direct-to-Chip Liquid Cooling",
    Universal_Presence: "Yes - #1 ABI ranking, all DCs need UPS/cooling",
    Investment_Tier: InvestmentTier.HighConviction,
    Geographic_Presence: "Global: Americas, EMEA, Asia",
    Recent_Contracts_2024_2025: "Liquid cooling portfolio for 120kW AI racks",
    Growth_Driver: "Integrated power/thermal management",
    Risk_Level: RiskLevel.Moderate,
    Competitive_Position: "Market Leader",
    Supply_Chain_Role: "Critical Infrastructure",
    Universal_Score: 93,
    Criticality: 10,
    Substitutability: "Moderate",
    YTD_Performance: 89.5,
    logoUrl: "https://logo.clearbit.com/vertiv.com",
    Country: "USA",
    Substitutability_Score: 40,
    Supply_Chain_Depth_Score: 40,
    SCSI: 280,
    ESG_Score: 60,
    PE_Ratio: 52.7,
    Forward_PE: 30.1,
    Revenue_Growth_YoY: 15.2,
    Debt_to_Equity: 2.5,
    Graham_Score: 3,
    isBlueChip: false,
  },
    {
    Company: "Prysmian",
    Ticker: "PRY.MI",
    Exchange: "Milan",
    Current_Price_USD: 95,
    Market_Cap_B: 27.5,
    Shares_Outstanding_M: 287,
    Float_Percent: 100,
    Category: "Interconnects",
    Sub_Category: "Power Cables",
    Product_Component: "HV/MV Power Distribution Cables",
    Universal_Presence: "Yes - World's largest cable mfg, all DC power",
    Investment_Tier: InvestmentTier.HighConviction,
    Geographic_Presence: "Global: Largest cable company",
    Recent_Contracts_2024_2025: "€382.5M contracts 2025, expansion globally",
    Growth_Driver: "Main power feeds, backbone infrastructure",
    Risk_Level: RiskLevel.Moderate,
    Competitive_Position: "Global Leader",
    Supply_Chain_Role: "Power Distribution",
    Universal_Score: 93,
    Criticality: 9,
    Substitutability: "Moderate",
    YTD_Performance: 35,
    logoUrl: "https://logo.clearbit.com/prysmiangroup.com",
    Country: "Italy",
    Substitutability_Score: 45,
    Supply_Chain_Depth_Score: 70,
    SCSI: 240,
    ESG_Score: 84,
    PE_Ratio: 18,
    Forward_PE: 15,
    Revenue_Growth_YoY: 6,
    Debt_to_Equity: 0.6,
    Graham_Score: 7,
    isBlueChip: false,
  },
  {
    Company: "Arista Networks",
    Ticker: "ANET",
    Exchange: "NYSE",
    Current_Price_USD: 398.6,
    Market_Cap_B: 125,
    Shares_Outstanding_M: 314,
    Float_Percent: 95,
    Category: "Networking",
    Sub_Category: "Ethernet Switches",
    Product_Component: "400G/800G Switches for AI Spine",
    Universal_Presence: "Yes - Every AI cluster uses high-speed Ethernet",
    Investment_Tier: InvestmentTier.HighConviction,
    Geographic_Presence: "Global: Cloud-native deployments",
    Recent_Contracts_2024_2025: "5 major AI trials, 70% cloud DC switching share",
    Growth_Driver: "Ethernet beating InfiniBand for AI",
    Risk_Level: RiskLevel.Moderate,
    Competitive_Position: "Market Leader",
    Supply_Chain_Role: "Critical Infrastructure",
    Universal_Score: 92,
    Criticality: 9,
    Substitutability: "Difficult",
    YTD_Performance: 34.2,
    logoUrl: "https://logo.clearbit.com/arista.com",
    Country: "USA",
    Substitutability_Score: 30,
    Supply_Chain_Depth_Score: 40,
    SCSI: 200,
    ESG_Score: 71,
    PE_Ratio: 45.1,
    Forward_PE: 35.8,
    Revenue_Growth_YoY: 16.3,
    Debt_to_Equity: 0,
    Graham_Score: 6,
    isBlueChip: false,
  },
  {
    Company: "Super Micro",
    Ticker: "SMCI",
    Exchange: "NASDAQ",
    Current_Price_USD: 850.5,
    Market_Cap_B: 50.1,
    Shares_Outstanding_M: 58.9,
    Float_Percent: 65,
    Category: "Hardware",
    Sub_Category: "AI Servers",
    Product_Component: "GPU Servers, Rack-Scale Systems",
    Universal_Presence: "Yes - #1 ABI agility, fastest new GPU adoption",
    Investment_Tier: InvestmentTier.OnRadar,
    Geographic_Presence: "Global: Design US, Asia manufacturing",
    Recent_Contracts_2024_2025: "Blackwell Ultra volume production Sept 2025",
    Growth_Driver: "First to market with new platforms",
    Risk_Level: RiskLevel.Aggressive,
    Competitive_Position: "Agile Leader",
    Supply_Chain_Role: "System Integrator",
    Universal_Score: 92,
    Criticality: 8,
    Substitutability: "Moderate",
    YTD_Performance: 190.2,
    logoUrl: "https://logo.clearbit.com/smci.com",
    Country: "USA",
    Substitutability_Score: 50,
    Supply_Chain_Depth_Score: 40,
    SCSI: 70,
    ESG_Score: 55,
    PE_Ratio: 45.8,
    Forward_PE: 22.3,
    Revenue_Growth_YoY: 200,
    Debt_to_Equity: 0.1,
    Graham_Score: 4,
    isBlueChip: false,
  },
  {
    Company: "GlobalWafers",
    Ticker: "6488.TWO",
    Exchange: "Taiwan",
    Current_Price_USD: 18,
    Market_Cap_B: 16,
    Shares_Outstanding_M: 887,
    Float_Percent: 70,
    Category: "Semiconductors",
    Sub_Category: "Silicon Wafers",
    Product_Component: "300mm Silicon Wafer Substrates",
    Universal_Presence: "Yes - Every chip starts as a wafer",
    Investment_Tier: InvestmentTier.MustBuy,
    Geographic_Presence: "Global: Taiwan, Texas (new)",
    Recent_Contracts_2024_2025: "$3B+ expansion, Texas fab opened May 2025",
    Growth_Driver: "Only 3 global suppliers for advanced wafers",
    Risk_Level: RiskLevel.High,
    Competitive_Position: "Oligopoly (Top 3)",
    Supply_Chain_Role: "Raw Material Supplier",
    Universal_Score: 92,
    Criticality: 9,
    Substitutability: "Difficult",
    YTD_Performance: -5.2,
    logoUrl: "https://logo.clearbit.com/sas-globalwafers.com",
    Country: "Taiwan",
    Substitutability_Score: 30,
    Supply_Chain_Depth_Score: 100,
    SCSI: 300,
    ESG_Score: 72,
    PE_Ratio: 12.1,
    Forward_PE: 10.5,
    Revenue_Growth_YoY: -18.7,
    Debt_to_Equity: 0.75,
    Graham_Score: 9,
    isBlueChip: false,
  },
  {
    Company: "SUMCO",
    Ticker: "3436.T",
    Exchange: "Tokyo",
    Current_Price_USD: 12.4,
    Market_Cap_B: 5,
    Shares_Outstanding_M: 405,
    Float_Percent: 85,
    Category: "Semiconductors",
    Sub_Category: "Silicon Wafers",
    Product_Component: "300mm Epitaxial Wafers",
    Universal_Presence: "Yes - Premium wafer supplier",
    Investment_Tier: InvestmentTier.MustBuy,
    Geographic_Presence: "Global: Japan, US (Oregon)",
    Recent_Contracts_2024_2025: "Advanced 300mm capacity expansion 2024-2025",
    Growth_Driver: "Elite wafer quality for AI/HPC",
    Risk_Level: RiskLevel.Moderate,
    Competitive_Position: "Oligopoly (Top 3)",
    Supply_Chain_Role: "Raw Material Supplier",
    Universal_Score: 91,
    Criticality: 9,
    Substitutability: "Difficult",
    YTD_Performance: 15.1,
    logoUrl: "https://logo.clearbit.com/sumcosi.com",
    Country: "Japan",
    Substitutability_Score: 30,
    Supply_Chain_Depth_Score: 100,
    SCSI: 290,
    ESG_Score: 78,
    PE_Ratio: 14.5,
    Forward_PE: 12,
    Revenue_Growth_YoY: -15,
    Debt_to_Equity: 0.3,
    Graham_Score: 8,
    isBlueChip: false,
  },
  {
    Company: "Eaton",
    Ticker: "ETN",
    Exchange: "NYSE",
    Current_Price_USD: 344.8,
    Market_Cap_B: 136,
    Shares_Outstanding_M: 395,
    Float_Percent: 99,
    Category: "Power & Cooling",
    Sub_Category: "UPS, Switchgear",
    Product_Component: "UPS Systems, Power Distribution",
    Universal_Presence: "Yes - Universal power management",
    Investment_Tier: InvestmentTier.HighConviction,
    Geographic_Presence: "Global: Industrial conglomerate",
    Recent_Contracts_2024_2025: "41-43% market share with Schneider, Vertiv",
    Growth_Driver: "Makes own circuit breakers (supply chain)",
    Risk_Level: RiskLevel.Conservative,
    Competitive_Position: "Market Leader",
    Supply_Chain_Role: "Critical Infrastructure",
    Universal_Score: 90,
    Criticality: 9,
    Substitutability: "Moderate",
    YTD_Performance: 39.1,
    logoUrl: "https://logo.clearbit.com/eaton.com",
    Country: "Ireland",
    Substitutability_Score: 60,
    Supply_Chain_Depth_Score: 40,
    SCSI: 220,
    ESG_Score: 80,
    PE_Ratio: 36.8,
    Forward_PE: 28.9,
    Revenue_Growth_YoY: 8,
    Debt_to_Equity: 0.6,
    Graham_Score: 8,
    isBlueChip: false,
  },
  {
    Company: "Murata",
    Ticker: "6981.T",
    Exchange: "Tokyo",
    Current_Price_USD: 19,
    Market_Cap_B: 34,
    Shares_Outstanding_M: 1790,
    Float_Percent: 80,
    Category: "Components",
    Sub_Category: "Passive Electronics",
    Product_Component: "MLCC Capacitors, Resistors",
    Universal_Presence: "Yes - Billions on every motherboard/PSU/board",
    Investment_Tier: InvestmentTier.OnRadar,
    Geographic_Presence: "Global: Japan base, worldwide",
    Recent_Contracts_2024_2025: "Supply chain localization, sustainability push",
    Growth_Driver: "Every PCB has Murata components",
    Risk_Level: RiskLevel.Aggressive,
    Competitive_Position: "Component Leader",
    Supply_Chain_Role: "Universal Component",
    Universal_Score: 90,
    Criticality: 9,
    Substitutability: "Moderate",
    YTD_Performance: 28,
    logoUrl: "https://logo.clearbit.com/murata.com",
    Country: "Japan",
    Substitutability_Score: 40,
    Supply_Chain_Depth_Score: 70,
    SCSI: 190,
    ESG_Score: 86,
    PE_Ratio: 18,
    Forward_PE: 16,
    Revenue_Growth_YoY: -5,
    Debt_to_Equity: 0.05,
    Graham_Score: 7,
    isBlueChip: false,
  },
    {
    Company: "TE Connectivity",
    Ticker: "TEL",
    Exchange: "NYSE",
    Current_Price_USD: 145.6,
    Market_Cap_B: 45,
    Shares_Outstanding_M: 309,
    Float_Percent: 99.5,
    Category: "Interconnects",
    Sub_Category: "Connectors, Sensors",
    Product_Component: "High-speed I/O connectors, Fiber Optics",
    Universal_Presence: "Ubiquitous",
    Investment_Tier: InvestmentTier.HighConviction,
    Geographic_Presence: "Global",
    Recent_Contracts_2024_2025: "High-speed I/O connectors for next-gen servers",
    Growth_Driver: "Higher data rates (800G/1.6T) driving connector demand",
    Risk_Level: RiskLevel.Conservative,
    Competitive_Position: "Established Leader",
    Supply_Chain_Role: "Core Component Supplier",
    Universal_Score: 90,
    Criticality: 8,
    Substitutability: "Difficult",
    YTD_Performance: 10.1,
    logoUrl: "https://logo.clearbit.com/te.com",
    Country: "Switzerland",
    Substitutability_Score: 30,
    Supply_Chain_Depth_Score: 70,
    SCSI: 210,
    ESG_Score: 84,
    PE_Ratio: 22,
    Forward_PE: 19.5,
    Revenue_Growth_YoY: -6.5,
    Debt_to_Equity: 0.35,
    Graham_Score: 7,
    isBlueChip: false,
  },
    {
    Company: "NVIDIA",
    Ticker: "NVDA",
    Exchange: "NASDAQ",
    Current_Price_USD: 120.89,
    Market_Cap_B: 2975,
    Shares_Outstanding_M: 24600,
    Float_Percent: 75.8,
    Category: "Semiconductors",
    Sub_Category: "GPUs",
    Product_Component: "H100/B200 Tensor Core GPUs",
    Universal_Presence: "Ubiquitous",
    Investment_Tier: InvestmentTier.MustBuy,
    Geographic_Presence: "Global",
    Recent_Contracts_2024_2025: "Major cloud providers (AWS, MSFT, GOOGL)",
    Growth_Driver: "Generative AI demand",
    Risk_Level: RiskLevel.Moderate,
    Competitive_Position: "Dominant Market Leader",
    Supply_Chain_Role: "Core Component Supplier",
    Universal_Score: 99,
    Criticality: 10,
    Substitutability: "Impossible",
    YTD_Performance: 144.5,
    logoUrl: "https://logo.clearbit.com/nvidia.com",
    Country: "USA",
    Substitutability_Score: 5,
    Supply_Chain_Depth_Score: 70,
    SCSI: 390,
    ESG_Score: 78,
    PE_Ratio: 70.5,
    Forward_PE: 45.2,
    Revenue_Growth_YoY: 262.1,
    Debt_to_Equity: 0.38,
    Graham_Score: 5,
    isBlueChip: true,
  },
  {
    Company: "Parker-Hannifin",
    Ticker: "PH",
    Exchange: "NYSE",
    Current_Price_USD: 520.15,
    Market_Cap_B: 65,
    Shares_Outstanding_M: 125,
    Float_Percent: 99,
    Category: "Power & Cooling",
    Sub_Category: "Fluid & Gas Handling",
    Product_Component: "Valves, Hoses, Fittings for Liquid Cooling",
    Universal_Presence: "Yes - Essential for all liquid cooling systems",
    Investment_Tier: InvestmentTier.OnRadar,
    Geographic_Presence: "Global",
    Recent_Contracts_2024_2025: "Increased demand from liquid cooling OEMs like Vertiv",
    Growth_Driver: "Shift to direct-to-chip and immersion cooling",
    Risk_Level: RiskLevel.Conservative,
    Competitive_Position: "Market Leader",
    Supply_Chain_Role: "Component Supplier",
    Universal_Score: 89,
    Criticality: 8,
    Substitutability: "Difficult",
    YTD_Performance: 18.5,
    logoUrl: "https://logo.clearbit.com/parker.com",
    Country: "USA",
    Substitutability_Score: 35,
    Supply_Chain_Depth_Score: 70,
    SCSI: 180,
    ESG_Score: 78,
    PE_Ratio: 24.1,
    Forward_PE: 19.8,
    Revenue_Growth_YoY: 3.2,
    Debt_to_Equity: 0.8,
    Graham_Score: 7,
    isBlueChip: false,
  },
  {
    Company: "Kingspan Group",
    Ticker: "KGP.L",
    Exchange: "LSE",
    Current_Price_USD: 95.50, // Converted from EUR
    Market_Cap_B: 17.5,
    Shares_Outstanding_M: 183,
    Float_Percent: 70,
    Category: "Construction",
    Sub_Category: "Physical Infrastructure",
    Product_Component: "Raised Access Flooring & Insulated Panels",
    Universal_Presence: "Yes - Standard in all modern data centers",
    Investment_Tier: InvestmentTier.OnRadar,
    Geographic_Presence: "Global",
    Recent_Contracts_2024_2025: "Major supplier for new hyperscale builds in Europe and US",
    Growth_Driver: "Data center construction boom requires specialized flooring",
    Risk_Level: RiskLevel.Moderate,
    Competitive_Position: "Market Leader",
    Supply_Chain_Role: "Structural Material",
    Universal_Score: 86,
    Criticality: 7,
    Substitutability: "Moderate",
    YTD_Performance: 22.1,
    logoUrl: "https://logo.clearbit.com/kingspan.com",
    Country: "Ireland",
    Substitutability_Score: 50,
    Supply_Chain_Depth_Score: 70,
    SCSI: 130,
    ESG_Score: 85,
    PE_Ratio: 25.0,
    Forward_PE: 20.5,
    Revenue_Growth_YoY: -5.0,
    Debt_to_Equity: 0.4,
    Graham_Score: 6,
    isBlueChip: false,
  },
  {
    Company: "Nextracker",
    Ticker: "NXT",
    Exchange: "NASDAQ",
    Current_Price_USD: 55.40,
    Market_Cap_B: 8.1,
    Shares_Outstanding_M: 146,
    Float_Percent: 85,
    Category: "Power & Cooling",
    Sub_Category: "Renewable Energy",
    Product_Component: "Solar Tracking Systems for Power Generation",
    Universal_Presence: "Growing - Key for DC renewable PPAs",
    Investment_Tier: InvestmentTier.OnRadar,
    Geographic_Presence: "Global",
    Recent_Contracts_2024_2025: "Contracts for large solar farms powering new data centers",
    Growth_Driver: "Push for 24/7 carbon-free energy for data centers",
    Risk_Level: RiskLevel.Aggressive,
    Competitive_Position: "Market Leader",
    Supply_Chain_Role: "Critical Infrastructure",
    Universal_Score: 82,
    Criticality: 6,
    Substitutability: "Difficult",
    YTD_Performance: 35.7,
    logoUrl: "https://logo.clearbit.com/nextracker.com",
    Country: "USA",
    Substitutability_Score: 40,
    Supply_Chain_Depth_Score: 40,
    SCSI: 150,
    ESG_Score: 70,
    PE_Ratio: 28.3,
    Forward_PE: 22.0,
    Revenue_Growth_YoY: 30.1,
    Debt_to_Equity: 0.1,
    Graham_Score: 5,
    isBlueChip: false,
  },
  // --- Stub data for remaining companies to reach 45 ---
  { Company: "Siemens", Ticker: "SIEGY", Exchange: "OTC", Current_Price_USD: 180.1, Market_Cap_B: 145, YTD_Performance: 12.5, logoUrl: "https://logo.clearbit.com/siemens.com", Country: "Germany", isBlueChip: false },
  { Company: "Atkore", Ticker: "ATKR", Exchange: "NYSE", Current_Price_USD: 140.5, Market_Cap_B: 4.8, YTD_Performance: -8.2, logoUrl: "https://logo.clearbit.com/atkore.com", Country: "USA", isBlueChip: false },
  { Company: "nVent Electric", Ticker: "NVT", Exchange: "NYSE", Current_Price_USD: 78.9, Market_Cap_B: 13, YTD_Performance: 25.1, logoUrl: "https://logo.clearbit.com/nvent.com", Country: "UK", isBlueChip: false },
  { Company: "Credo Technology", Ticker: "CRDO", Exchange: "NASDAQ", Current_Price_USD: 163.61, Market_Cap_B: 2.8, YTD_Performance: 110.4, logoUrl: "https://logo.clearbit.com/credosemi.com", Country: "USA", isBlueChip: false },
  { Company: "Seagate", Ticker: "STX", Exchange: "NASDAQ", Current_Price_USD: 105.2, Market_Cap_B: 21, YTD_Performance: 21.5, logoUrl: "https://logo.clearbit.com/seagate.com", Country: "Ireland", isBlueChip: false },
  { Company: "Western Digital", Ticker: "WDC", Exchange: "NASDAQ", Current_Price_USD: 82.4, Market_Cap_B: 25, YTD_Performance: 68.9, logoUrl: "https://logo.clearbit.com/westerndigital.com", Country: "USA", isBlueChip: false },
  { Company: "Caterpillar", Ticker: "CAT", Exchange: "NYSE", Current_Price_USD: 389.2, Market_Cap_B: 195, YTD_Performance: 31.2, logoUrl: "https://logo.clearbit.com/caterpillar.com", Country: "USA", isBlueChip: false },
  { Company: "Cummins", Ticker: "CMI", Exchange: "NYSE", Current_Price_USD: 312.4, Market_Cap_B: 43, YTD_Performance: 20.3, logoUrl: "https://logo.clearbit.com/cummins.com", Country: "USA", isBlueChip: false },
  { Company: "Dell Technologies", Ticker: "DELL", Exchange: "NYSE", Current_Price_USD: 126.8, Market_Cap_B: 91, YTD_Performance: 65.7, logoUrl: "https://logo.clearbit.com/dell.com", Country: "USA", isBlueChip: true },
  { Company: "YAGEO", Ticker: "2327.TW", Exchange: "Taiwan", Current_Price_USD: 17, Market_Cap_B: 3.7, YTD_Performance: 8.4, logoUrl: "https://logo.clearbit.com/yageo.com", Country: "Taiwan", isBlueChip: false },
  { Company: "Vishay", Ticker: "VSH", Exchange: "NYSE", Current_Price_USD: 15.8, Market_Cap_B: 2.3, YTD_Performance: -15.6, logoUrl: "https://logo.clearbit.com/vishay.com", Country: "USA", isBlueChip: false },
  { Company: "TTM Technologies", Ticker: "TTMI", Exchange: "NASDAQ", Current_Price_USD: 16.45, Market_Cap_B: 1.7, YTD_Performance: 18.1, logoUrl: "https://logo.clearbit.com/ttm.com", Country: "USA", isBlueChip: false },
  { Company: "Sanmina", Ticker: "SANM", Exchange: "NASDAQ", Current_Price_USD: 63.2, Market_Cap_B: 3.8, YTD_Performance: 5.3, logoUrl: "https://logo.clearbit.com/sanmina.com", Country: "USA", isBlueChip: false },
  { Company: "Jabil", Ticker: "JBL", Exchange: "NYSE", Current_Price_USD: 120.5, Market_Cap_B: 15.8, YTD_Performance: 2.9, logoUrl: "https://logo.clearbit.com/jabil.com", Country: "USA", isBlueChip: false },
  { Company: "Dow", Ticker: "DOW", Exchange: "NYSE", Current_Price_USD: 51.2, Market_Cap_B: 35, YTD_Performance: -4.8, logoUrl: "https://logo.clearbit.com/dow.com", Country: "USA", isBlueChip: false },
  { Company: "DuPont", Ticker: "DD", Exchange: "NYSE", Current_Price_USD: 84.6, Market_Cap_B: 36, YTD_Performance: 10.2, logoUrl: "https://logo.clearbit.com/dupont.com", Country: "USA", isBlueChip: false },
  { Company: "PPG Industries", Ticker: "PPG", Exchange: "NYSE", Current_Price_USD: 128.4, Market_Cap_B: 30, YTD_Performance: -12.1, logoUrl: "https://logo.clearbit.com/ppg.com", Country: "USA", isBlueChip: false },
  { Company: "EnerSys", Ticker: "ENS", Exchange: "NYSE", Current_Price_USD: 102.3, Market_Cap_B: 4.2, YTD_Performance: 6.7, logoUrl: "https://logo.clearbit.com/enersys.com", Country: "USA", isBlueChip: false },
  { Company: "Carrier Global", Ticker: "CARR", Exchange: "NYSE", Current_Price_USD: 78.5, Market_Cap_B: 62, YTD_Performance: 15.8, logoUrl: "https://logo.clearbit.com/carrier.com", Country: "USA", isBlueChip: false },
  { Company: "Trane Technologies", Ticker: "TT", Exchange: "NYSE", Current_Price_USD: 368.2, Market_Cap_B: 84, YTD_Performance: 45.3, logoUrl: "https://logo.clearbit.com/tranetechnologies.com", Country: "Ireland", isBlueChip: false },
  { Company: "Honeywell", Ticker: "HON", Exchange: "NASDAQ", Current_Price_USD: 215.3, Market_Cap_B: 142, YTD_Performance: 3.1, logoUrl: "https://logo.clearbit.com/honeywell.com", Country: "USA", isBlueChip: false },
  { Company: "Johnson Controls", Ticker: "JCI", Exchange: "NYSE", Current_Price_USD: 76.4, Market_Cap_B: 49, YTD_Performance: 20.9, logoUrl: "https://logo.clearbit.com/johnsoncontrols.com", Country: "Ireland", isBlueChip: false },
  { Company: "Coherent", Ticker: "COHR", Exchange: "NASDAQ", Current_Price_USD: 87.2, Market_Cap_B: 13, YTD_Performance: 75.2, logoUrl: "https://logo.clearbit.com/coherent.com", Country: "USA", isBlueChip: false },
  { Company: "Emerson Electric", Ticker: "EMR", Exchange: "NYSE", Current_Price_USD: 118.7, Market_Cap_B: 69, YTD_Performance: 22.4, logoUrl: "https://logo.clearbit.com/emerson.com", Country: "USA", isBlueChip: false },
  { Company: "Signify", Ticker: "LIGHT.AS", Exchange: "Amsterdam", Current_Price_USD: 48.2, Market_Cap_B: 6.5, YTD_Performance: -8.8, logoUrl: "https://logo.clearbit.com/signify.com", Country: "Netherlands", isBlueChip: false },
  { Company: "ABB", Ticker: "ABB", Exchange: "NYSE", Current_Price_USD: 48.2, Market_Cap_B: 86, YTD_Performance: 25.7, logoUrl: "https://logo.clearbit.com/global.abb", Country: "Switzerland", isBlueChip: false },
  { Company: "Entegris", Ticker: "ENTG", Exchange: "NASDAQ", Current_Price_USD: 135.1, Market_Cap_B: 20.4, YTD_Performance: 30.1, logoUrl: "https://logo.clearbit.com/entegris.com", Country: "USA", isBlueChip: false },
  { Company: "Chemours", Ticker: "CC", Exchange: "NYSE", Current_Price_USD: 25.8, Market_Cap_B: 3.9, YTD_Performance: -18.2, logoUrl: "https://logo.clearbit.com/chemours.com", Country: "USA", isBlueChip: false },
  { Company: "Vulcan Materials", Ticker: "VMC", Exchange: "NYSE", Current_Price_USD: 264.3, Market_Cap_B: 35, YTD_Performance: 10.6, logoUrl: "https://logo.clearbit.com/vulcanmaterials.com", Country: "USA", isBlueChip: false },
  { Company: "Martin Marietta", Ticker: "MLM", Exchange: "NYSE", Current_Price_USD: 523.4, Market_Cap_B: 32, YTD_Performance: 5.9, logoUrl: "https://logo.clearbit.com/martinmarietta.com", Country: "USA", isBlueChip: false },
].map((c: any) => {
    // This map function provides default values for the stubbed data to prevent runtime errors.
    const defaults = {
        Shares_Outstanding_M: c.Market_Cap_B * 1000 / c.Current_Price_USD,
        Float_Percent: 95,
        Category: "Components",
        Sub_Category: "Various",
        Product_Component: "Various critical components",
        Universal_Presence: "Yes",
        Investment_Tier: InvestmentTier.OnRadar,
        Geographic_Presence: "Global",
        Recent_Contracts_2024_2025: "Ongoing supply to major OEMs",
        Growth_Driver: "Data center expansion",
        Risk_Level: RiskLevel.Moderate,
        Competitive_Position: "Major Player",
        Supply_Chain_Role: "Component Supplier",
        Universal_Score: 85 + (Math.random() - 0.5) * 10,
        Criticality: 7 + Math.floor(Math.random() * 2),
        Substitutability: "Moderate" as const,
        Substitutability_Score: 60,
        Supply_Chain_Depth_Score: 70,
        SCSI: 150 + Math.floor(Math.random() * 50),
        ESG_Score: 75,
        PE_Ratio: 25 + (Math.random() - 0.5) * 10,
        Forward_PE: 20 + (Math.random() - 0.5) * 8,
        Revenue_Growth_YoY: 10 + (Math.random() - 0.5) * 15,
        Debt_to_Equity: 0.5 + (Math.random() - 0.5) * 0.4,
        Graham_Score: 6 + Math.floor(Math.random() * 3),
        isBlueChip: false,
    };
    return { ...defaults, ...c };
}));